// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project b917fc1195920e6c "Portfolio", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Default' | 'Loading' | 'Hidden' // Variant
 * click?: Function // Click
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-L2MJKLZT.js";
import { routes } from "./chunks/chunk-MBSQQC4T.js";

// virtual:button-load-more
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/skjJsChzuS2o29XbFZcj/nUmCCm3Dxs6iDlUo0rPJ/IEKQTOVXq.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	RichText,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
	withOptimizedAppearEffect,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var MotionDivWithFX = withFX(motion.div);
var MotionDivWithFXWithOptimizedAppearEffect = withOptimizedAppearEffect(
	withFX(motion.div),
);
var enabledGestures = {
	mQGOuxi7O: {
		hover: true,
	},
};
var cycleOrder = ["mQGOuxi7O", "H3_UEJB9m", "qRmNhYxL8"];
var serializationHash = "framer-Z9BBb";
var variantClassNames = {
	H3_UEJB9m: "framer-v-10tif6g",
	mQGOuxi7O: "framer-v-fg335d",
	qRmNhYxL8: "framer-v-pa6ejt",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var transition2 = {
	delay: 0,
	duration: 0.3,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var animation = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition2,
	x: 0,
	y: 0,
};
var animation1 = {
	opacity: 1e-3,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 0,
};
var transition3 = {
	delay: 0,
	duration: 1,
	ease: [0, 0, 1, 1],
	type: "tween",
};
var animation2 = {
	opacity: 1,
	rotate: 360,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 0,
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	Default: "mQGOuxi7O",
	Hidden: "qRmNhYxL8",
	Loading: "H3_UEJB9m",
};
var getProps = ({ click, height, id, width, ...props }) => {
	var _humanReadableVariantMap_props_variant, _ref;
	return {
		...props,
		variant:
			(_ref =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref !== void 0
				? _ref
				: "mQGOuxi7O",
		Wld3NDzSj: click !== null && click !== void 0 ? click : props.Wld3NDzSj,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Variants = motion.create(React.Fragment);
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		Wld3NDzSj,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "mQGOuxi7O",
		enabledGestures,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTapn9xadi = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		if (Wld3NDzSj) {
			const res = await Wld3NDzSj(...args);
			if (res === false) return false;
		}
	});
	const sharedStyleClassNames = [className];
	const isDisplayed = () => {
		if (baseVariant === "qRmNhYxL8") return false;
		return true;
	};
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const ref1 = React.useRef(null);
	const isDisplayed1 = () => {
		if (baseVariant === "H3_UEJB9m") return false;
		return true;
	};
	const isDisplayed2 = () => {
		if (baseVariant === "H3_UEJB9m") return true;
		return false;
	};
	const defaultLayoutId = React.useId();
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants animate={variants} initial={false}>
				{isDisplayed() && (
					<Transition value={transition1}>
						<motion.div
							{...restProps}
							{...gestureHandlers}
							className={cx(
								scopingClassNames,
								"framer-fg335d",
								className2,
								classNames,
							)}
							data-framer-name={"Default"}
							data-highlight={true}
							layoutDependency={layoutDependency}
							layoutId={"mQGOuxi7O"}
							onTap={onTapn9xadi}
							ref={ref !== null && ref !== void 0 ? ref : ref1}
							style={{
								backgroundColor:
									"var(--token-041fe102-52af-45fc-9163-7f47a549ff42, rgb(245, 245, 245))",
								...style,
							}}
							variants={{
								"mQGOuxi7O-hover": {
									backgroundColor:
										"var(--token-e9abed44-df8b-4765-bbfe-7c072006d47b, rgb(0, 0, 0))",
								},
							}}
							{...addPropertyOverrides(
								{
									"mQGOuxi7O-hover": {
										"data-framer-name": void 0,
									},
									H3_UEJB9m: {
										"data-framer-name": "Loading",
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							{isDisplayed1() && (
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1ejl53n"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"SIAfsOdaE"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-e9abed44-df8b-4765-bbfe-7c072006d47b, rgb(0, 0, 0))",
									}}
									variants={{
										"mQGOuxi7O-hover": {
											"--extracted-r6o4lv":
												"var(--token-c21010f9-5cb6-4d3d-85fc-4227a6481949, rgb(255, 255, 255))",
										},
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											"mQGOuxi7O-hover": {
												children: (
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-1l7bfec"}
															data-styles-preset={"T3pYYFndi"}
															style={{
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-c21010f9-5cb6-4d3d-85fc-4227a6481949, rgb(255, 255, 255)))",
															}}
														>
															{"Load More"}
														</motion.p>
													</React.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-1l7bfec"}
											data-styles-preset={"T3pYYFndi"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-e9abed44-df8b-4765-bbfe-7c072006d47b, rgb(0, 0, 0)))",
											}}
										>
											{"Load More"}
										</motion.p>
									</React.Fragment>
								</RichText>
							)}
							{isDisplayed2() && (
								<MotionDivWithFXWithOptimizedAppearEffect
									__perspectiveFX={false}
									__smartComponentFX={true}
									__targetOpacity={1}
									animate={animation}
									className={"framer-9ujmf7"}
									data-framer-appear-id={"9ujmf7"}
									data-framer-name={"Spinner"}
									initial={animation1}
									layoutDependency={layoutDependency}
									layoutId={"RMR8vLpXX"}
									optimized={true}
									style={{
										mask: "url('https://framerusercontent.com/images/pGiXYozQ3mE4cilNOItfe2L2fUA.svg') alpha no-repeat center / cover add",
										WebkitMask:
											"url('https://framerusercontent.com/images/pGiXYozQ3mE4cilNOItfe2L2fUA.svg') alpha no-repeat center / cover add",
									}}
								>
									<MotionDivWithFX
										__framer__loop={animation2}
										__framer__loopEffectEnabled={true}
										__framer__loopRepeatDelay={0}
										__framer__loopRepeatType={"loop"}
										__framer__loopTransition={transition3}
										__perspectiveFX={false}
										__smartComponentFX={true}
										__targetOpacity={1}
										className={"framer-zoxbxi"}
										data-framer-name={"Conic"}
										layoutDependency={layoutDependency}
										layoutId={"JCeon6uEb"}
										style={{
											background:
												'conic-gradient(from 0deg at 50% 50%, rgba(255, 255, 255, 0) 0deg, var(--token-e9abed44-df8b-4765-bbfe-7c072006d47b, rgb(0, 0, 0)) /* {"name":"Black"} */ 342deg)',
										}}
									>
										<motion.div
											className={"framer-zo2qse"}
											data-framer-name={"Round"}
											layoutDependency={layoutDependency}
											layoutId={"uTTAghfxj"}
											style={{
												backgroundColor:
													"var(--token-e9abed44-df8b-4765-bbfe-7c072006d47b, rgb(0, 0, 0))",
												borderBottomLeftRadius: 1,
												borderBottomRightRadius: 1,
												borderTopLeftRadius: 1,
												borderTopRightRadius: 1,
											}}
										/>
									</MotionDivWithFX>
								</MotionDivWithFXWithOptimizedAppearEffect>
							)}
						</motion.div>
					</Transition>
				)}
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-Z9BBb.framer-7gpv3u, .framer-Z9BBb .framer-7gpv3u { display: block; }",
	".framer-Z9BBb.framer-fg335d { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; padding: 20px 36px 20px 36px; position: relative; width: min-content; }",
	".framer-Z9BBb .framer-1ejl53n { -webkit-user-select: none; flex: none; height: auto; position: relative; user-select: none; white-space: pre; width: auto; }",
	".framer-Z9BBb .framer-9ujmf7 { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 20px); overflow: visible; position: relative; width: 20px; }",
	".framer-Z9BBb .framer-zoxbxi { bottom: 0px; flex: none; left: 0px; overflow: visible; position: absolute; right: 0px; top: 0px; }",
	".framer-Z9BBb .framer-zo2qse { flex: none; height: 2px; left: calc(50.00000000000002% - 2px / 2); overflow: visible; position: absolute; top: 0px; width: 2px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-Z9BBb.framer-fg335d { gap: 0px; } .framer-Z9BBb.framer-fg335d > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-Z9BBb.framer-fg335d > :first-child { margin-left: 0px; } .framer-Z9BBb.framer-fg335d > :last-child { margin-right: 0px; } }",
	".framer-Z9BBb.framer-v-10tif6g.framer-fg335d { width: 148px; }",
	...css,
];
var FramerIEKQTOVXq = withCSS(Component, css2, "framer-Z9BBb");
var stdin_default = FramerIEKQTOVXq;
FramerIEKQTOVXq.displayName = "Button - Load More";
FramerIEKQTOVXq.defaultProps = {
	height: 57.5,
	width: 148,
};
addPropertyControls(FramerIEKQTOVXq, {
	variant: {
		options: ["mQGOuxi7O", "H3_UEJB9m", "qRmNhYxL8"],
		optionTitles: ["Default", "Loading", "Hidden"],
		title: "Variant",
		type: ControlType.Enum,
	},
	Wld3NDzSj: {
		title: "Click",
		type: ControlType.EventHandler,
	},
});
addFonts(
	FramerIEKQTOVXq,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:button-load-more
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "mQGOuxi7O",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"b917fc1195920e6c8a50255315bde13451700c9dc2ee3323349c54f78331e19f"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ButtonLoadMoreFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"b917fc1195920e6c8a50255315bde13451700c9dc2ee3323349c54f78331e19f"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var button_load_more_default = ComponentWithRoot;
export { button_load_more_default as default };
