// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project b917fc1195920e6c "Portfolio", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Normal' | 'Small' // Variant
 * cursor?: undefined // Cursor
 * link?: string // Link
 * title?: string // Title
 * newTab?: boolean // New Tab
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-L2MJKLZT.js";
import { routes } from "./chunks/chunk-MBSQQC4T.js";

// virtual:button-white-bg
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/nP2ey1Y7ajtQDboyGMRX/oREI07roupbnGy50sOKH/TAwhfLYAI.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	Link,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var enabledGestures = {
	RAbXymraV: {
		hover: true,
	},
	z_ucP0_Sp: {
		hover: true,
	},
};
var cycleOrder = ["z_ucP0_Sp", "RAbXymraV"];
var serializationHash = "framer-DfSJc";
var variantClassNames = {
	RAbXymraV: "framer-v-1o32dlh",
	z_ucP0_Sp: "framer-v-1nc25n9",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Normal: "z_ucP0_Sp",
	Small: "RAbXymraV",
};
var getProps = ({
	cursor,
	height,
	id,
	link,
	newTab,
	title,
	width,
	...props
}) => {
	var _ref, _humanReadableVariantMap_props_variant, _ref1;
	return {
		...props,
		EDKDKpsgs: link !== null && link !== void 0 ? link : props.EDKDKpsgs,
		FYA_sD0B3:
			(_ref = title !== null && title !== void 0 ? title : props.FYA_sD0B3) !==
				null && _ref !== void 0
				? _ref
				: "Show More",
		lXMPtAaP7: newTab !== null && newTab !== void 0 ? newTab : props.lXMPtAaP7,
		oY9MofvWl: cursor !== null && cursor !== void 0 ? cursor : props.oY9MofvWl,
		variant:
			(_ref1 =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref1 !== void 0
				? _ref1
				: "z_ucP0_Sp",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		oY9MofvWl,
		EDKDKpsgs,
		FYA_sD0B3,
		lXMPtAaP7,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "z_ucP0_Sp",
		enabledGestures,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [className];
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<Link href={EDKDKpsgs} nodeId={"z_ucP0_Sp"} openInNewTab={lXMPtAaP7}>
						<motion.a
							{...restProps}
							{...gestureHandlers}
							className={`${cx(serializationHash, ...sharedStyleClassNames, "framer-1nc25n9", className2, classNames)} framer-yr1nsy`}
							data-framer-cursor={oY9MofvWl}
							data-framer-name={"Normal"}
							layoutDependency={layoutDependency}
							layoutId={"z_ucP0_Sp"}
							ref={ref !== null && ref !== void 0 ? ref : ref1}
							style={{
								backgroundColor:
									"var(--token-041fe102-52af-45fc-9163-7f47a549ff42, rgb(245, 245, 245))",
								...style,
							}}
							variants={{
								"RAbXymraV-hover": {
									backgroundColor:
										"var(--token-e9abed44-df8b-4765-bbfe-7c072006d47b, rgb(0, 0, 0))",
								},
								"z_ucP0_Sp-hover": {
									backgroundColor:
										"var(--token-e9abed44-df8b-4765-bbfe-7c072006d47b, rgb(0, 0, 0))",
								},
							}}
							{...addPropertyOverrides(
								{
									"RAbXymraV-hover": {
										"data-framer-name": void 0,
									},
									"z_ucP0_Sp-hover": {
										"data-framer-name": void 0,
									},
									RAbXymraV: {
										"data-framer-name": "Small",
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-uuuchi"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"iegXwNDzG"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-e9abed44-df8b-4765-bbfe-7c072006d47b, rgb(0, 0, 0))",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={FYA_sD0B3}
								variants={{
									"RAbXymraV-hover": {
										"--extracted-r6o4lv":
											"var(--token-c21010f9-5cb6-4d3d-85fc-4227a6481949, rgb(255, 255, 255))",
									},
									"z_ucP0_Sp-hover": {
										"--extracted-r6o4lv":
											"var(--token-c21010f9-5cb6-4d3d-85fc-4227a6481949, rgb(255, 255, 255))",
									},
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										"RAbXymraV-hover": {
											children: (
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-1l7bfec"}
														data-styles-preset={"T3pYYFndi"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-c21010f9-5cb6-4d3d-85fc-4227a6481949, rgb(255, 255, 255)))",
														}}
													>
														{"Show More"}
													</motion.p>
												</React.Fragment>
											),
										},
										"z_ucP0_Sp-hover": {
											children: (
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-1l7bfec"}
														data-styles-preset={"T3pYYFndi"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-c21010f9-5cb6-4d3d-85fc-4227a6481949, rgb(255, 255, 255)))",
														}}
													>
														{"Show More"}
													</motion.p>
												</React.Fragment>
											),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-1l7bfec"}
										data-styles-preset={"T3pYYFndi"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-e9abed44-df8b-4765-bbfe-7c072006d47b, rgb(0, 0, 0)))",
										}}
									>
										{"Show More"}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-DfSJc.framer-yr1nsy, .framer-DfSJc .framer-yr1nsy { display: block; }",
	".framer-DfSJc.framer-1nc25n9 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 20px 36px 20px 36px; position: relative; text-decoration: none; width: min-content; }",
	".framer-DfSJc .framer-uuuchi { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-DfSJc.framer-1nc25n9 { gap: 0px; } .framer-DfSJc.framer-1nc25n9 > * { margin: 0px; margin-bottom: calc(10px / 2); margin-top: calc(10px / 2); } .framer-DfSJc.framer-1nc25n9 > :first-child { margin-top: 0px; } .framer-DfSJc.framer-1nc25n9 > :last-child { margin-bottom: 0px; } }",
	".framer-DfSJc.framer-v-1o32dlh.framer-1nc25n9 { padding: 16px 26px 16px 26px; }",
	...css,
];
var FramerTAwhfLYAI = withCSS(Component, css2, "framer-DfSJc");
var stdin_default = FramerTAwhfLYAI;
FramerTAwhfLYAI.displayName = "Button - White BG";
FramerTAwhfLYAI.defaultProps = {
	height: 57.5,
	width: 152.5,
};
addPropertyControls(FramerTAwhfLYAI, {
	variant: {
		options: ["z_ucP0_Sp", "RAbXymraV"],
		optionTitles: ["Normal", "Small"],
		title: "Variant",
		type: ControlType.Enum,
	},
	oY9MofvWl: {
		title: "Cursor",
		type: ControlType.CustomCursor,
	},
	EDKDKpsgs: {
		title: "Link",
		type: ControlType.Link,
	},
	FYA_sD0B3: {
		defaultValue: "Show More",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	lXMPtAaP7: {
		defaultValue: false,
		title: "New Tab",
		type: ControlType.Boolean,
	},
});
addFonts(
	FramerTAwhfLYAI,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:button-white-bg
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "RAbXymraV",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"b917fc1195920e6c8a50255315bde13451700c9dc2ee3323349c54f78331e19f"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ButtonWhiteBgFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"b917fc1195920e6c8a50255315bde13451700c9dc2ee3323349c54f78331e19f"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var button_white_bg_default = ComponentWithRoot;
export { button_white_bg_default as default };
