// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project b917fc1195920e6c "Portfolio", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * email?: string // Email
 * clipboard?: string // Clipboard
}} Props

 */
import { routes } from "./chunks/chunk-MBSQQC4T.js";

// virtual:copy-email
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/nIVjOXyMdug5PGA8Nbu4/QOPQJ6B4mQanEC1TUgwr/dUuo7K1ic.js
import { jsx as _jsx2, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider,
	ControlType as ControlType5,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	RichText,
	SVG,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion as motion2, MotionConfigContext } from "unframer";
import * as React3 from "react";

// /:https://framerusercontent.com/modules/Hj20QU19p80mpYsvesiZ/RfHh9MIwqlgi04HKZ3Qo/Clipboard.js
import { jsx as _jsx } from "react/jsx-runtime";
import { useCallback as useCallback2 } from "react";
import { addPropertyControls, ControlType as ControlType4 } from "unframer";
import { motion } from "unframer";

// /:https://framerusercontent.com/modules/VTUDdizacRHpwbkOamr7/AykinQJbgwl92LvMGZwu/constants.js
import { ControlType } from "unframer";
var fontStack = `"Inter", system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"`;
var containerStyles = {
	position: "relative",
	width: "100%",
	height: "100%",
	display: "flex",
	justifyContent: "center",
	alignItems: "center",
};
var emptyStateStyle = {
	...containerStyles,
	borderRadius: 6,
	background: "rgba(136, 85, 255, 0.3)",
	color: "#85F",
	border: "1px dashed #85F",
	flexDirection: "column",
};
var defaultEvents = {
	onClick: {
		type: ControlType.EventHandler,
	},
	onMouseEnter: {
		type: ControlType.EventHandler,
	},
	onMouseLeave: {
		type: ControlType.EventHandler,
	},
};
var fontSizeOptions = {
	type: ControlType.Number,
	title: "Font Size",
	min: 2,
	max: 200,
	step: 1,
	displayStepper: true,
};
var fontControls = {
	font: {
		type: ControlType.Boolean,
		title: "Font",
		defaultValue: false,
		disabledTitle: "Default",
		enabledTitle: "Custom",
	},
	fontFamily: {
		type: ControlType.String,
		title: "Family",
		placeholder: "Inter",
		hidden: ({ font }) => !font,
	},
	fontWeight: {
		type: ControlType.Enum,
		title: "Weight",
		options: [100, 200, 300, 400, 500, 600, 700, 800, 900],
		optionTitles: [
			"Thin",
			"Extra-light",
			"Light",
			"Regular",
			"Medium",
			"Semi-bold",
			"Bold",
			"Extra-bold",
			"Black",
		],
		hidden: ({ font }) => !font,
	},
};

// /:https://framerusercontent.com/modules/D4TWeLfcxT6Tysr2BlYg/iZjmqdxVx1EOiM3k1FaW/useOnNavigationTargetChange.js
import { useIsInCurrentNavigationTarget } from "unframer";
import { useEffect } from "react";

// /:https://framerusercontent.com/modules/ExNgrA7EJTKUPpH6vIlN/eiOrSJ2Ab5M9jPCvVwUz/useConstant.js
import { useRef } from "react";

// /:https://framerusercontent.com/modules/D2Lz5CmnNVPZFFiZXalt/QaCzPbriZBfXWZIIycFI/colorFromToken.js
import { Color } from "unframer";

// /:https://framerusercontent.com/modules/3mKFSGQqKHV82uOV1eBc/5fbRLvOpxZC0JOXugvwm/isMotionValue.js
import { MotionValue } from "unframer";

// /:https://framerusercontent.com/modules/xDiQsqBGXzmMsv7AlEVy/uhunpMiNsbXxzjlXsg1y/useUniqueClassName.js
import * as React from "react";

// /:https://framerusercontent.com/modules/ETACN5BJyFTSo0VVDJfu/NHRqowOiXkF9UwOzczF7/variantUtils.js
import { ControlType as ControlType2 } from "unframer";

// /:https://framerusercontent.com/modules/eMBrwoqQK7h6mEeGQUH8/GuplvPJVjmxpk9zqOTcb/isBrowser.js
import { useMemo } from "react";

// /:https://framerusercontent.com/modules/v9AWX2URmiYsHf7GbctE/XxKAZ9KlhWqf5x1JMyyF/useOnChange.js
import { useEffect as useEffect3 } from "react";

// /:https://framerusercontent.com/modules/kNDwabfjDEb3vUxkQlZS/fSIr3AOAYbGlfSPgXpYu/useAutoMotionValue.js
import { useCallback, useEffect as useEffect4, useRef as useRef2 } from "react";
import { motionValue, animate, RenderTarget } from "unframer";

// /:https://framerusercontent.com/modules/cuQH4dmpDnV8YK1mSgQX/KqRXqunFjE6ufhpc7ZRu/useFontControls.js
import { fontStore } from "unframer";
import { useEffect as useEffect5 } from "react";
var fontWeights = {
	100: "Thin",
	200: "Extra-light",
	300: "Light",
	400: "Regular",
	500: "Medium",
	600: "Semi-bold",
	700: "Bold",
	800: "Extra-bold",
	900: "Black",
};
function useFontControls(props) {
	const {
		fontFamily = "Inter",
		fontSize = 16,
		fontWeight = 400,
		font = false,
	} = props;
	const fontWeightName = fontWeights[fontWeight];
	const customFontStack = `"${fontFamily} ${fontWeightName}", "${fontFamily}", ${fontStack}`;
	const fontFamilyStyle = fontFamily
		? {
				fontSize,
				fontWeight,
				fontFamily: customFontStack,
			}
		: {
				fontSize,
				fontWeight,
			};
	const fetchCustomFonts = async () => {
		await fontStore
			.loadWebFontsFromSelectors([
				`CUSTOM;${fontFamily}`,
				`CUSTOM;${fontFamily} ${fontWeightName}`,
				`GF;${fontFamily}-${fontWeightName.toLowerCase()}`,
			])
			.catch((e) => console.error(e));
	};
	useEffect5(() => {
		if (font) fetchCustomFonts();
	}, [font, fontFamily, fontWeight]);
	return fontFamilyStyle;
}

// /:https://framerusercontent.com/modules/afBE9Yx1W6bY5q32qPxe/m3q7puE2tbo1S2C0s0CT/useRenderTarget.js
import { useMemo as useMemo2 } from "react";
import { RenderTarget as RenderTarget2 } from "unframer";

// /:https://framerusercontent.com/modules/zGkoP8tPDCkoBzMdt5uq/0zFSjxIYliHxrQQnryFX/useControlledState.js
import * as React2 from "react";

// /:https://framerusercontent.com/modules/5SM58HxZHxjjv7aLMOgQ/WXz9i6mVki0bBCrKdqB3/propUtils.js
import { useMemo as useMemo3 } from "react";
import { ControlType as ControlType3 } from "unframer";
function useRadius(props) {
	const {
		borderRadius,
		isMixedBorderRadius,
		topLeftRadius,
		topRightRadius,
		bottomRightRadius,
		bottomLeftRadius,
	} = props;
	const radiusValue = useMemo3(
		() =>
			isMixedBorderRadius
				? `${topLeftRadius}px ${topRightRadius}px ${bottomRightRadius}px ${bottomLeftRadius}px`
				: `${borderRadius}px`,
		[
			borderRadius,
			isMixedBorderRadius,
			topLeftRadius,
			topRightRadius,
			bottomRightRadius,
			bottomLeftRadius,
		],
	);
	return radiusValue;
}
var borderRadiusControl = {
	borderRadius: {
		title: "Radius",
		type: ControlType3.FusedNumber,
		toggleKey: "isMixedBorderRadius",
		toggleTitles: ["Radius", "Radius per corner"],
		valueKeys: [
			"topLeftRadius",
			"topRightRadius",
			"bottomRightRadius",
			"bottomLeftRadius",
		],
		valueLabels: ["TL", "TR", "BR", "BL"],
		min: 0,
	},
};
function usePadding(props) {
	const {
		padding,
		paddingPerSide,
		paddingTop,
		paddingRight,
		paddingBottom,
		paddingLeft,
	} = props;
	const paddingValue = useMemo3(
		() =>
			paddingPerSide
				? `${paddingTop}px ${paddingRight}px ${paddingBottom}px ${paddingLeft}px`
				: padding,
		[
			padding,
			paddingPerSide,
			paddingTop,
			paddingRight,
			paddingBottom,
			paddingLeft,
		],
	);
	return paddingValue;
}
var paddingControl = {
	padding: {
		type: ControlType3.FusedNumber,
		toggleKey: "paddingPerSide",
		toggleTitles: ["Padding", "Padding per side"],
		valueKeys: ["paddingTop", "paddingRight", "paddingBottom", "paddingLeft"],
		valueLabels: ["T", "R", "B", "L"],
		min: 0,
		title: "Padding",
	},
};

// /:https://framerusercontent.com/modules/Hj20QU19p80mpYsvesiZ/RfHh9MIwqlgi04HKZ3Qo/Clipboard.js
var __unframerWindow = typeof window !== "undefined" ? window : void 0;
var __unframerNavigator =
	typeof __unframerWindow !== "undefined" ? navigator : void 0;
function Clipboard(props) {
	const {
		label,
		content,
		fill,
		color,
		style,
		onClick,
		font,
		hoverOptions,
		...rest
	} = props;
	const deprecatedFont = useFontControls({
		fontWeight: 500,
		...rest,
	});
	const borderRadius = useRadius(props);
	const paddingValue = usePadding(props);
	const handleClick = useCallback2(() => {
		var ref;
		(ref = __unframerNavigator.clipboard) === null || ref === void 0
			? void 0
			: ref.writeText(content);
		onClick === null || onClick === void 0 ? void 0 : onClick();
	}, [onClick, content]);
	return (
		<motion.button
			style={{
				border: "none",
				outline: "none",
				resize: "none",
				width: "max-content",
				wordBreak: "break-word",
				overflowWrap: "break-word",
				WebkitTapHighlightColor: "rgba(0, 0, 0, 0)",
				letterSpacing: "-0.2px",
				display: "flex",
				justifyContent: "center",
				alignItems: "center",
				background: fill,
				borderRadius,
				cursor: "pointer",
				padding: paddingValue,
				color,
				...deprecatedFont,
				...font,
				...style,
			}}
			onClick={handleClick}
			{...rest}
			whileHover={hoverOptions}
			transition={
				hoverOptions === null || hoverOptions === void 0
					? void 0
					: hoverOptions.transition
			}
		>
			{label}
		</motion.button>
	);
}
addPropertyControls(Clipboard, {
	content: {
		type: ControlType4.String,
		title: "Content",
		displayTextArea: true,
		description: "When clicked, this content will be copied to the clipboard.",
	},
	label: {
		type: ControlType4.String,
		title: "Label",
		defaultValue: "Copy to Clipboard",
	},
	fill: {
		type: ControlType4.Color,
		title: "Fill",
		defaultValue: "#06F",
	},
	color: {
		type: ControlType4.Color,
		title: "Text",
		defaultValue: "#fff",
	},
	font: {
		// @ts-ignore - Internal
		type: ControlType4.Font,
		controls: "extended",
		defaultValue: {
			fontSize: 16,
		},
	},
	hoverOptions: {
		type: ControlType4.Object,
		title: "Hover",
		buttonTitle: "Effect",
		optional: true,
		controls: {
			scale: {
				type: ControlType4.Number,
				title: "Scale",
				min: 0,
				max: 10,
				displayStepper: true,
				step: 0.01,
				defaultValue: 1.1,
			},
			backgroundColor: {
				type: ControlType4.Color,
				title: "Fill",
				defaultValue: "#0088FF",
				optional: true,
			},
			color: {
				type: ControlType4.Color,
				title: "Color",
				defaultValue: "#FFF",
				optional: true,
			},
			transition: {
				type: ControlType4.Transition,
				title: "Transition",
				defaultValue: {
					type: "spring",
					stiffness: 400,
					damping: 30,
				},
			},
		},
	},
	padding: {
		type: ControlType4.FusedNumber,
		toggleKey: "paddingPerSide",
		toggleTitles: ["Padding", "Padding per side"],
		valueKeys: ["paddingTop", "paddingRight", "paddingBottom", "paddingLeft"],
		valueLabels: ["T", "R", "B", "L"],
		min: 0,
		title: "Padding",
		defaultValue: 10,
	},
	borderRadius: {
		title: "Radius",
		type: ControlType4.FusedNumber,
		toggleKey: "isMixedBorderRadius",
		toggleTitles: ["Radius", "Radius per corner"],
		valueKeys: [
			"topLeftRadius",
			"topRightRadius",
			"bottomRightRadius",
			"bottomLeftRadius",
		],
		valueLabels: ["TL", "TR", "BR", "BL"],
		min: 0,
		defaultValue: 50,
	},
	...defaultEvents,
});

// /:https://framerusercontent.com/modules/5KOaIKb3a1N5EHtZL1qB/hgK1PuNDdhHscdzyklMj/mOcUED3wf.js
import { fontStore as fontStore2 } from "unframer";
fontStore2.loadFonts([
	"Inter-Medium",
	"Inter-Bold",
	"Inter-BoldItalic",
	"Inter-MediumItalic",
]);
var fonts = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/5A3Ce6C9YYmCjpQx9M4inSaKU.woff2",
				weight: "500",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/Qx95Xyt0Ka3SGhinnbXIGpEIyP4.woff2",
				weight: "500",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/6mJuEAguuIuMog10gGvH5d3cl8.woff2",
				weight: "500",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/xYYWaj7wCU5zSQH0eXvSaS19wo.woff2",
				weight: "500",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/otTaNuNpVK4RbdlT7zDDdKvQBA.woff2",
				weight: "500",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/d3tHnaQIAeqiE5hGcRw4mmgWYU.woff2",
				weight: "500",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/DolVirEGb34pEXEp8t8FQBSK4.woff2",
				weight: "500",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/DpPBYI0sL4fYLgAkX8KXOPVt7c.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/4RAEQdEOrcnDkhHiiCbJOw92Lk.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/1K3W8DizY3v4emK8Mb08YHxTbs.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/tUSCtfYVM1I1IchuyCwz9gDdQ.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/VgYFWiwsAC5OYxAycRXXvhze58.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/DXD0Q7LSl7HEvDzucnyLnGBHM.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "normal",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/GIryZETIX4IFypco5pYZONKhJIo.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/H89BbHkbHDzlxZzxi8uPzTsp90.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/u6gJwDuwB143kpNK1T1MDKDWkMc.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/43sJ6MfOPh1LCJt46OvyDuSbA6o.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/wccHG0r4gBDAIRhfHiOlq6oEkqw.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/WZ367JPwf9bRW6LdTHN8rXgSjw.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/QxmhnWTzLtyjIiZcfaLIJ8EFBXU.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/2A4Xx7CngadFGlVV4xrO06OBHY.woff2",
				weight: "700",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/khkJkwSL66WFg8SX6Wa726c.woff2",
				weight: "500",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/0E7IMbDzcGABpBwwqNEt60wU0w.woff2",
				weight: "500",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/NTJ0nQgIF0gcDelS14zQ9NR9Q.woff2",
				weight: "500",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/QrcNhgEPfRl0LS8qz5Ln8olanl8.woff2",
				weight: "500",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/JEXmejW8mXOYMtt0hyRg811kHac.woff2",
				weight: "500",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/ksvR4VsLksjpSwnC2fPgHRNMw.woff2",
				weight: "500",
			},
			{
				family: "Inter",
				source: "framer",
				style: "italic",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/uy9s0iWuxiNnVt8EpTI3gzohpwo.woff2",
				weight: "500",
			},
		],
	},
];
var css = [
	'.framer-Ifylc .framer-styles-preset-1p380mk:not(.rich-text-wrapper), .framer-Ifylc .framer-styles-preset-1p380mk.rich-text-wrapper p { --framer-font-family: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 26px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 500; --framer-letter-spacing: -0.06em; --framer-line-height: 1.3em; --framer-paragraph-spacing: 20px; --framer-text-alignment: justify; --framer-text-color: var(--token-e9abed44-df8b-4765-bbfe-7c072006d47b, #000000); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
];
var className = "framer-Ifylc";

// /:https://framerusercontent.com/modules/nIVjOXyMdug5PGA8Nbu4/QOPQJ6B4mQanEC1TUgwr/dUuo7K1ic.js
var ClipboardFonts = getFonts(Clipboard);
var serializationHash = "framer-4Kte5";
var variantClassNames = {
	ykIzwcGWK: "framer-v-1k1k2p1",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React3.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React3.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var getProps = ({ clipboard, email, height, id, width, ...props }) => {
	var _ref, _ref1;
	return {
		...props,
		qbajx_C0v:
			(_ref = email !== null && email !== void 0 ? email : props.qbajx_C0v) !==
				null && _ref !== void 0
				? _ref
				: "hello@yume.com",
		xLpBSQbDh:
			(_ref1 =
				clipboard !== null && clipboard !== void 0
					? clipboard
					: props.xLpBSQbDh) !== null && _ref1 !== void 0
				? _ref1
				: "helllo",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Variants = motion2.create(React3.Fragment);
var Component = /* @__PURE__ */ React3.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		qbajx_C0v,
		xLpBSQbDh,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "ykIzwcGWK",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const ref1 = React3.useRef(null);
	const defaultLayoutId = React3.useId();
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion2.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1k1k2p1",
							className2,
							classNames,
						)}
						data-framer-name={"Email"}
						layoutDependency={layoutDependency}
						layoutId={"ykIzwcGWK"}
						ref={ref !== null && ref !== void 0 ? ref : ref1}
						style={{
							...style,
						}}
					>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-x0dm4m"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"eOKJn3jqZ"}
							style={{
								"--extracted-r6o4lv":
									"var(--token-e9abed44-df8b-4765-bbfe-7c072006d47b, rgb(0, 0, 0))",
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							text={qbajx_C0v}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React3.Fragment>
								<motion2.p
									className={"framer-styles-preset-1p380mk"}
									data-styles-preset={"mOcUED3wf"}
									style={{
										"--framer-text-color":
											"var(--extracted-r6o4lv, var(--token-e9abed44-df8b-4765-bbfe-7c072006d47b, rgb(0, 0, 0)))",
									}}
								>
									{"hello@yume.com"}
								</motion2.p>
							</React3.Fragment>
						</RichText>
						<SVG
							className={"framer-si6i9f"}
							data-framer-name={"Copy icon"}
							layout={"position"}
							layoutDependency={layoutDependency}
							layoutId={"ehsmfaMXW"}
							opacity={1}
							svg={
								'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 20 20"><g id="ss9734463342_1"><path d="M 0 0 L 20 0 L 20 20 L 0 20 Z" fill="transparent"></path><path d="M 13.89 1.668 L 1.668 1.668 L 1.668 13.89 L 13.89 13.89 Z" fill="transparent" stroke-width="2" stroke="rgb(0, 0, 0)" stroke-linecap="round" stroke-linejoin="round" stroke-dasharray=""></path><path d="M 17 6.11 L 18.332 6.11 L 18.332 18.332 L 6.109 18.332 L 6.109 17" fill="transparent" stroke-width="2" stroke="rgb(0, 0, 0)" stroke-linecap="round" stroke-linejoin="round" stroke-dasharray=""></path></g></svg>'
							}
							svgContentId={9734463342}
							withExternalLayout={true}
						/>
						<ComponentViewportProvider>
							<motion2.div
								className={"framer-1xp7gg4-container"}
								layoutDependency={layoutDependency}
								layoutId={"CBA5OkIHe-container"}
							>
								<Clipboard
									borderRadius={0}
									bottomLeftRadius={0}
									bottomRightRadius={0}
									color={"rgba(255, 255, 255, 0)"}
									content={xLpBSQbDh}
									fill={"rgba(0, 102, 255, 0)"}
									font={{}}
									height={"100%"}
									id={"CBA5OkIHe"}
									isMixedBorderRadius={false}
									label={"Copy to Clipboard"}
									layoutId={"CBA5OkIHe"}
									padding={10}
									paddingBottom={10}
									paddingLeft={10}
									paddingPerSide={false}
									paddingRight={10}
									paddingTop={10}
									style={{
										height: "100%",
										width: "100%",
									}}
									topLeftRadius={0}
									topRightRadius={0}
									width={"100%"}
								/>
							</motion2.div>
						</ComponentViewportProvider>
					</motion2.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-4Kte5.framer-1v8ryws, .framer-4Kte5 .framer-1v8ryws { display: block; }",
	".framer-4Kte5.framer-1k1k2p1 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
	".framer-4Kte5 .framer-x0dm4m { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-4Kte5 .framer-si6i9f { flex: none; height: 20px; position: relative; width: 20px; }",
	".framer-4Kte5 .framer-1xp7gg4-container { bottom: 0px; flex: none; left: 0px; position: absolute; right: 0px; top: 0px; z-index: 1; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-4Kte5.framer-1k1k2p1 { gap: 0px; } .framer-4Kte5.framer-1k1k2p1 > * { margin: 0px; margin-left: calc(12px / 2); margin-right: calc(12px / 2); } .framer-4Kte5.framer-1k1k2p1 > :first-child { margin-left: 0px; } .framer-4Kte5.framer-1k1k2p1 > :last-child { margin-right: 0px; } }",
	...css,
];
var FramerdUuo7K1ic = withCSS(Component, css2, "framer-4Kte5");
var stdin_default = FramerdUuo7K1ic;
FramerdUuo7K1ic.displayName = "Copy email";
FramerdUuo7K1ic.defaultProps = {
	height: 34,
	width: 226,
};
addPropertyControls2(FramerdUuo7K1ic, {
	qbajx_C0v: {
		defaultValue: "hello@yume.com",
		displayTextArea: false,
		title: "Email",
		type: ControlType5.String,
	},
	xLpBSQbDh: {
		defaultValue: "helllo",
		displayTextArea: true,
		title: "Clipboard",
		type: ControlType5.String,
	},
});
addFonts(
	FramerdUuo7K1ic,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...ClipboardFonts,
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:copy-email
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"b917fc1195920e6c8a50255315bde13451700c9dc2ee3323349c54f78331e19f"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders CopyEmailFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"b917fc1195920e6c8a50255315bde13451700c9dc2ee3323349c54f78331e19f"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var copy_email_default = ComponentWithRoot;
export { copy_email_default as default };
