// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project b917fc1195920e6c "Portfolio", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * cursor?: undefined // Cursor
}} Props

 */
import {
	className as className3,
	className2 as className4,
	className3 as className6,
	className4 as className7,
	className5 as className8,
	css as css3,
	css2 as css4,
	css3 as css6,
	css4 as css7,
	css5 as css8,
	fonts as fonts3,
	fonts2 as fonts4,
	fonts3 as fonts6,
	fonts4 as fonts7,
	fonts5 as fonts8,
} from "./chunks/chunk-6FQH6EUW.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-57F2Y2KU.js";
import {
	className as className5,
	className2 as className9,
	css as css5,
	css2 as css9,
	fonts as fonts5,
	fonts2 as fonts9,
} from "./chunks/chunk-L7BTO3WG.js";
import { className, css, fonts } from "./chunks/chunk-FPFTPTOS.js";
import { routes } from "./chunks/chunk-MBSQQC4T.js";

// virtual:faq-accordion
import { Fragment as Fragment3 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/gNd8xvtpTR0jkXDQu0tA/0WxIdmwryaffBTL8OIeC/VQTLOg4nE.js
import { jsx as _jsx2, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider,
	ControlType as ControlType2,
	cx as cx2,
	getFonts,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";

// /:https://framerusercontent.com/modules/dY4zL4X4QeVZHZD0jVf9/sOEQIW2cICKKvoNFuMji/SKxaVD4px.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	RichText,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var cycleOrder = ["j8b0XeksZ", "tsfkqMxRe"];
var serializationHash = "framer-WP7mF";
var variantClassNames = {
	j8b0XeksZ: "framer-v-1ifzft3",
	tsfkqMxRe: "framer-v-1it3rgc",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transition1 = {
	delay: 0,
	duration: 0.3,
	ease: [0, 0, 0, 0.96],
	type: "tween",
};
var transformTemplate1 = (_, t) => `translate(-50%, -50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Close: "j8b0XeksZ",
	Open: "tsfkqMxRe",
};
var getProps = ({ answer, cursor, height, id, question, width, ...props }) => {
	var _ref, _ref1, _humanReadableVariantMap_props_variant, _ref2;
	return {
		...props,
		mEpK4TMVu:
			(_ref =
				answer !== null && answer !== void 0 ? answer : props.mEpK4TMVu) !==
				null && _ref !== void 0 ? (
				_ref
			) : (
				<React.Fragment>
					<motion.p>
						{
							"The timeline varies depending on the complexity of the project. Typically, smaller projects like a logo design or single-page website take 1-2 weeks, while larger projects such as full brand identity or multi-page websites can take 4-6 weeks. I\u2019ll provide a detailed timeline once we define the scope of the project, and I always aim to deliver on time."
						}
					</motion.p>
				</React.Fragment>
			),
		OWaIPd7ml:
			(_ref1 =
				question !== null && question !== void 0
					? question
					: props.OWaIPd7ml) !== null && _ref1 !== void 0
				? _ref1
				: "Question",
		variant:
			(_ref2 =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref2 !== void 0
				? _ref2
				: "j8b0XeksZ",
		wusxffIuT: cursor !== null && cursor !== void 0 ? cursor : props.wusxffIuT,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className10,
		layoutId,
		variant,
		OWaIPd7ml,
		mEpK4TMVu,
		wusxffIuT,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "j8b0XeksZ",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTap1mj3noo = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		setVariant("tsfkqMxRe");
	});
	const onTapc1prij = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		setVariant("j8b0XeksZ");
	});
	const ref1 = React.useRef(null);
	const isDisplayed = () => {
		if (baseVariant === "tsfkqMxRe") return false;
		return true;
	};
	const isDisplayed1 = () => {
		if (baseVariant === "tsfkqMxRe") return true;
		return false;
	};
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [
		className8,
		className7,
		className6,
		className2,
		className,
		className4,
		className9,
		className5,
		className3,
	];
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							serializationHash,
							...sharedStyleClassNames,
							"framer-1ifzft3",
							className10,
							classNames,
						)}
						data-framer-cursor={wusxffIuT}
						data-framer-name={"Close"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"j8b0XeksZ"}
						onTap={onTap1mj3noo}
						ref={ref !== null && ref !== void 0 ? ref : ref1}
						style={{
							backgroundColor:
								"var(--token-041fe102-52af-45fc-9163-7f47a549ff42, rgb(245, 245, 245))",
							...style,
						}}
						{...addPropertyOverrides(
							{
								tsfkqMxRe: {
									"data-framer-cursor": void 0,
									"data-framer-name": "Open",
									onTap: onTapc1prij,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-o4v0yd"}
							data-framer-name={"Title"}
							layoutDependency={layoutDependency}
							layoutId={"pz3yweb5Z"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-ecbxjn"}
								data-framer-name={"Title"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"Y0UBlOyNi"}
								style={{
									"--extracted-1w1cjl5":
										"var(--token-e9abed44-df8b-4765-bbfe-7c072006d47b, rgb(0, 0, 0))",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={OWaIPd7ml}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.h6
										className={"framer-styles-preset-1uzx9i5"}
										data-styles-preset={"sNZTrSlRJ"}
										style={{
											"--framer-text-color":
												"var(--extracted-1w1cjl5, var(--token-e9abed44-df8b-4765-bbfe-7c072006d47b, rgb(0, 0, 0)))",
										}}
									>
										{"Question"}
									</motion.h6>
								</React.Fragment>
							</RichText>
							<motion.div
								className={"framer-3nxvtq"}
								data-framer-name={"Icon"}
								layoutDependency={layoutDependency}
								layoutId={"Bl9pPsWWZ"}
								style={{
									rotate: 0,
								}}
								variants={{
									tsfkqMxRe: {
										rotate: 90,
									},
								}}
							>
								{isDisplayed() && (
									<motion.div
										className={"framer-19qqorg"}
										layoutDependency={layoutDependency}
										layoutId={"dPpcmiQAm"}
										style={{
											backgroundColor:
												"var(--token-e9abed44-df8b-4765-bbfe-7c072006d47b, rgb(0, 0, 0))",
										}}
									/>
								)}
								<motion.div
									className={"framer-ir218a"}
									layoutDependency={layoutDependency}
									layoutId={"ezR0PrW9h"}
									style={{
										backgroundColor:
											"var(--token-e9abed44-df8b-4765-bbfe-7c072006d47b, rgb(0, 0, 0))",
										rotate: 90,
									}}
									transformTemplate={transformTemplate1}
									{...addPropertyOverrides(
										{
											tsfkqMxRe: {
												transformTemplate: void 0,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								/>
							</motion.div>
						</motion.div>
						{isDisplayed1() && (
							<motion.div
								className={"framer-y47nqx"}
								data-framer-name={"Panel"}
								layoutDependency={layoutDependency}
								layoutId={"PG23Balr4"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1ypsluo"}
									data-framer-name={"text"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"AJFbNsrp_"}
									style={{
										"--extracted-r6o4lv": "rgb(35, 35, 35)",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									stylesPresetsClassNames={{
										a: "framer-styles-preset-dsdgjd",
										code: "framer-styles-preset-1hozuru",
										h1: "framer-styles-preset-bglb1i",
										h2: "framer-styles-preset-1miokle",
										h3: "framer-styles-preset-elkczp",
										h4: "framer-styles-preset-v5rub6",
										h5: "framer-styles-preset-1gvuoy3",
										h6: "framer-styles-preset-1uzx9i5",
										p: "framer-styles-preset-124zfba",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									{mEpK4TMVu}
								</RichText>
							</motion.div>
						)}
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css10 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-WP7mF.framer-rmsnkw, .framer-WP7mF .framer-rmsnkw { display: block; }",
	".framer-WP7mF.framer-1ifzft3 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 728px; }",
	".framer-WP7mF .framer-o4v0yd { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: hidden; padding: 40px; position: relative; width: 100%; }",
	".framer-WP7mF .framer-ecbxjn { flex: 1 0 0px; height: auto; max-width: 80%; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-WP7mF .framer-3nxvtq { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 22px); overflow: hidden; position: relative; width: 22px; }",
	".framer-WP7mF .framer-19qqorg { flex: none; height: 2px; left: calc(50.00000000000002% - 14px / 2); overflow: visible; position: absolute; top: calc(50.00000000000002% - 2px / 2); width: 14px; }",
	".framer-WP7mF .framer-ir218a { aspect-ratio: 8 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 2px); left: 50%; overflow: visible; position: absolute; top: 50%; width: 14px; }",
	".framer-WP7mF .framer-y47nqx { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: hidden; padding: 0px 40px 40px 40px; position: relative; width: 100%; }",
	".framer-WP7mF .framer-1ypsluo { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-WP7mF.framer-1ifzft3 { gap: 0px; } .framer-WP7mF.framer-1ifzft3 > * { margin: 0px; margin-bottom: calc(0px / 2); margin-top: calc(0px / 2); } .framer-WP7mF.framer-1ifzft3 > :first-child { margin-top: 0px; } .framer-WP7mF.framer-1ifzft3 > :last-child { margin-bottom: 0px; } }",
	".framer-WP7mF.framer-v-1it3rgc .framer-o4v0yd { padding: 40px 40px 30px 40px; }",
	".framer-WP7mF.framer-v-1it3rgc .framer-ir218a { aspect-ratio: unset; height: 2px; left: calc(50.00000000000002% - 14px / 2); top: calc(50.00000000000002% - 1.75px / 2); }",
	...css8,
	...css7,
	...css6,
	...css2,
	...css,
	...css4,
	...css9,
	...css5,
	...css3,
];
var FramerSKxaVD4px = withCSS(Component, css10, "framer-WP7mF");
var stdin_default = FramerSKxaVD4px;
FramerSKxaVD4px.displayName = "FAQ";
FramerSKxaVD4px.defaultProps = {
	height: 102,
	width: 728,
};
addPropertyControls(FramerSKxaVD4px, {
	variant: {
		options: ["j8b0XeksZ", "tsfkqMxRe"],
		optionTitles: ["Close", "Open"],
		title: "Variant",
		type: ControlType.Enum,
	},
	OWaIPd7ml: {
		defaultValue: "Question",
		displayTextArea: false,
		title: "Question",
		type: ControlType.String,
	},
	mEpK4TMVu: {
		defaultValue:
			"<p>The timeline varies depending on the complexity of the project. Typically, smaller projects like a logo design or single-page website take 1-2 weeks, while larger projects such as full brand identity or multi-page websites can take 4-6 weeks. I\u2019ll provide a detailed timeline once we define the scope of the project, and I always aim to deliver on time.</p>",
		title: "Answer",
		type: ControlType.RichText,
	},
	wusxffIuT: {
		title: "Cursor",
		type: ControlType.CustomCursor,
	},
});
addFonts(
	FramerSKxaVD4px,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts8),
		...getFontsFromSharedStyle(fonts7),
		...getFontsFromSharedStyle(fonts6),
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts4),
		...getFontsFromSharedStyle(fonts9),
		...getFontsFromSharedStyle(fonts5),
		...getFontsFromSharedStyle(fonts3),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/gNd8xvtpTR0jkXDQu0tA/0WxIdmwryaffBTL8OIeC/VQTLOg4nE.js
var FAQFonts = getFonts(stdin_default);
var serializationHash2 = "framer-bDhkl";
var variantClassNames2 = {
	LqN0gfi5J: "framer-v-8wh7tv",
};
var transition12 = {
	delay: 0,
	duration: 0.3,
	ease: [0, 0, 0, 0.96],
	type: "tween",
};
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion2.create(React2.Fragment);
var getProps2 = ({ cursor, height, id, width, ...props }) => {
	return {
		...props,
		NL785k100: cursor !== null && cursor !== void 0 ? cursor : props.NL785k100,
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo2();
	const {
		style,
		className: className10,
		layoutId,
		variant,
		NL785k100,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		defaultVariant: "LqN0gfi5J",
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const ref1 = React2.useRef(null);
	const defaultLayoutId = React2.useId();
	const sharedStyleClassNames = [];
	const componentViewport = useComponentViewport2();
	return (
		<LayoutGroup2
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition12}>
					<motion2.div
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							serializationHash2,
							...sharedStyleClassNames,
							"framer-8wh7tv",
							className10,
							classNames,
						)}
						data-framer-name={"FAQ"}
						layoutDependency={layoutDependency}
						layoutId={"LqN0gfi5J"}
						ref={ref !== null && ref !== void 0 ? ref : ref1}
						style={{
							...style,
						}}
					>
						<ComponentViewportProvider
							height={102}
							width={
								(componentViewport === null || componentViewport === void 0
									? void 0
									: componentViewport.width) || "100vw"
							}
							y={
								((componentViewport === null || componentViewport === void 0
									? void 0
									: componentViewport.y) || 0) +
								0 +
								0
							}
						>
							<motion2.div
								className={"framer-1ywnv0g-container"}
								layoutDependency={layoutDependency}
								layoutId={"RHhGVGPme-container"}
							>
								{_jsx2(stdin_default, {
									height: "100%",
									id: "RHhGVGPme",
									layoutId: "RHhGVGPme",
									mEpK4TMVu: (
										<React2.Fragment>
											<p>
												{
													"My design process starts with fully understanding your goals and needs. I begin with research and brainstorming to gather insights, followed by sketching initial concepts. Once we agree on a creative direction, I develop detailed designs and make revisions based on your feedback. I strive for a seamless, collaborative process, ensuring that each step brings us closer to the perfect solution."
												}
											</p>
										</React2.Fragment>
									),
									OWaIPd7ml: "What is your creative design process like?",
									style: {
										width: "100%",
									},
									variant: "j8b0XeksZ",
									width: "100%",
									wusxffIuT: NL785k100,
								})}
							</motion2.div>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={102}
							width={
								(componentViewport === null || componentViewport === void 0
									? void 0
									: componentViewport.width) || "100vw"
							}
							y={
								((componentViewport === null || componentViewport === void 0
									? void 0
									: componentViewport.y) || 0) +
								0 +
								112
							}
						>
							<motion2.div
								className={"framer-u1dxad-container"}
								layoutDependency={layoutDependency}
								layoutId={"CYfTRKFmx-container"}
							>
								{_jsx2(stdin_default, {
									height: "100%",
									id: "CYfTRKFmx",
									layoutId: "CYfTRKFmx",
									mEpK4TMVu: (
										<React2.Fragment>
											<p>
												{
													"The timeline varies depending on the complexity of the project. Typically, smaller projects like a logo design or single-page website take 1-2 weeks, while larger projects such as full brand identity or multi-page websites can take 4-6 weeks. I\u2019ll provide a detailed project timeline once we define the scope of the project, and I always aim to deliver on time."
												}
											</p>
										</React2.Fragment>
									),
									OWaIPd7ml: "What is your typical project timeline?",
									style: {
										width: "100%",
									},
									variant: "j8b0XeksZ",
									width: "100%",
									wusxffIuT: NL785k100,
								})}
							</motion2.div>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={102}
							width={
								(componentViewport === null || componentViewport === void 0
									? void 0
									: componentViewport.width) || "100vw"
							}
							y={
								((componentViewport === null || componentViewport === void 0
									? void 0
									: componentViewport.y) || 0) +
								0 +
								224
							}
						>
							<motion2.div
								className={"framer-w73b3l-container"}
								layoutDependency={layoutDependency}
								layoutId={"CiW4TYD_h-container"}
							>
								{_jsx2(stdin_default, {
									height: "100%",
									id: "CiW4TYD_h",
									layoutId: "CiW4TYD_h",
									mEpK4TMVu: (
										<React2.Fragment>
											<p>
												{
													"Getting started is easy! Simply reach out through the contact form or send me an email with details about your project. We\u2019ll schedule an initial consultation to discuss your vision, goals, and requirements. From there, I\u2019ll create a tailored proposal outlining the project scope, timeline, and pricing. Once everything is agreed upon, we can immediately start the creative process!"
												}
											</p>
										</React2.Fragment>
									),
									OWaIPd7ml: "How do I get started on a project with you?",
									style: {
										width: "100%",
									},
									variant: "j8b0XeksZ",
									width: "100%",
									wusxffIuT: NL785k100,
								})}
							</motion2.div>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={102}
							width={
								(componentViewport === null || componentViewport === void 0
									? void 0
									: componentViewport.width) || "100vw"
							}
							y={
								((componentViewport === null || componentViewport === void 0
									? void 0
									: componentViewport.y) || 0) +
								0 +
								336
							}
						>
							<motion2.div
								className={"framer-zx821a-container"}
								layoutDependency={layoutDependency}
								layoutId={"X1GygR9uF-container"}
							>
								{_jsx2(stdin_default, {
									height: "100%",
									id: "X1GygR9uF",
									layoutId: "X1GygR9uF",
									mEpK4TMVu: (
										<React2.Fragment>
											<p>
												{
													"If I'm currently fully booked, don\u2019t worry! I maintain a waiting list, and I\u2019ll notify you as soon as I have availability. I recommend reaching out as early as possible to secure a spot in my schedule. In the meantime, I\u2019m happy to offer guidance or advice on preparing for the project so we can hit the ground running once I\u2019m available."
												}
											</p>
										</React2.Fragment>
									),
									OWaIPd7ml: "What should I do if you're fully booked?",
									style: {
										width: "100%",
									},
									variant: "j8b0XeksZ",
									width: "100%",
									wusxffIuT: NL785k100,
								})}
							</motion2.div>
						</ComponentViewportProvider>
					</motion2.div>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css11 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-bDhkl.framer-e435lw, .framer-bDhkl .framer-e435lw { display: block; }",
	".framer-bDhkl.framer-8wh7tv { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 728px; }",
	".framer-bDhkl .framer-1ywnv0g-container, .framer-bDhkl .framer-u1dxad-container, .framer-bDhkl .framer-w73b3l-container, .framer-bDhkl .framer-zx821a-container { flex: none; height: auto; position: relative; width: 100%; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-bDhkl.framer-8wh7tv { gap: 0px; } .framer-bDhkl.framer-8wh7tv > * { margin: 0px; margin-bottom: calc(10px / 2); margin-top: calc(10px / 2); } .framer-bDhkl.framer-8wh7tv > :first-child { margin-top: 0px; } .framer-bDhkl.framer-8wh7tv > :last-child { margin-bottom: 0px; } }",
];
var FramerVQTLOg4nE = withCSS2(Component2, css11, "framer-bDhkl");
var stdin_default2 = FramerVQTLOg4nE;
FramerVQTLOg4nE.displayName = "FAQ Accordion";
FramerVQTLOg4nE.defaultProps = {
	height: 438,
	width: 728,
};
addPropertyControls2(FramerVQTLOg4nE, {
	NL785k100: {
		title: "Cursor",
		type: ControlType2.CustomCursor,
	},
});
addFonts2(
	FramerVQTLOg4nE,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...FAQFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:faq-accordion
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"b917fc1195920e6c8a50255315bde13451700c9dc2ee3323349c54f78331e19f"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders FaqAccordionFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"b917fc1195920e6c8a50255315bde13451700c9dc2ee3323349c54f78331e19f"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var faq_accordion_default = ComponentWithRoot;
export { faq_accordion_default as default };
