// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project b917fc1195920e6c "Portfolio", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Tablet' | 'Phone' // Variant
 * cursor?: undefined // Cursor
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-L2MJKLZT.js";
import {
	className as className3,
	className2 as className4,
	css as css3,
	css2 as css4,
	fonts as fonts3,
	fonts2 as fonts4,
} from "./chunks/chunk-L7BTO3WG.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-FPFTPTOS.js";
import { routes } from "./chunks/chunk-MBSQQC4T.js";

// virtual:footer
import { Fragment as Fragment3 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/rsGe4CHXeARxFZ5mTON5/4FAI0DkDmGYrZt1YoDTf/VY9qRujfw.js
import { jsx as _jsx2, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider,
	ControlType as ControlType2,
	cx as cx2,
	getFonts,
	getFontsFromSharedStyle as getFontsFromSharedStyle2,
	Link as Link2,
	ResolveLinks,
	RichText as RichText2,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useRouter,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
	withFX,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";

// /:https://framerusercontent.com/modules/i3PiihJiues8AqtTlQbo/hy6B87irEABQ2rmj61Js/KsAZ0KnKd.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	Link,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var enabledGestures = {
	s3LxAv_48: {
		hover: true,
	},
};
var serializationHash = "framer-6zg8S";
var variantClassNames = {
	s3LxAv_48: "framer-v-9w2via",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({
	cursor,
	height,
	id,
	link,
	newTab,
	title,
	width,
	...props
}) => {
	var _ref;
	return {
		...props,
		GhxBoxfgA: cursor !== null && cursor !== void 0 ? cursor : props.GhxBoxfgA,
		oGjGfyY3A: link !== null && link !== void 0 ? link : props.oGjGfyY3A,
		xrHA2Kp0H:
			(_ref = title !== null && title !== void 0 ? title : props.xrHA2Kp0H) !==
				null && _ref !== void 0
				? _ref
				: "Show More",
		zgrV9HxLK: newTab !== null && newTab !== void 0 ? newTab : props.zgrV9HxLK,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className5,
		layoutId,
		variant,
		GhxBoxfgA,
		xrHA2Kp0H,
		oGjGfyY3A,
		zgrV9HxLK,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "s3LxAv_48",
		enabledGestures,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [className];
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<Link href={oGjGfyY3A} nodeId={"s3LxAv_48"} openInNewTab={zgrV9HxLK}>
						<motion.a
							{...restProps}
							{...gestureHandlers}
							className={`${cx(serializationHash, ...sharedStyleClassNames, "framer-9w2via", className5, classNames)} framer-1n96x1o`}
							data-framer-cursor={GhxBoxfgA}
							data-framer-name={"Button"}
							layoutDependency={layoutDependency}
							layoutId={"s3LxAv_48"}
							ref={ref !== null && ref !== void 0 ? ref : ref1}
							style={{
								backgroundColor:
									"var(--token-c21010f9-5cb6-4d3d-85fc-4227a6481949, rgb(255, 255, 255))",
								...style,
							}}
							variants={{
								"s3LxAv_48-hover": {
									backgroundColor:
										"var(--token-2c41600e-9419-4c92-a082-e20b249b03ac, rgb(51, 51, 51))",
								},
							}}
							{...addPropertyOverrides(
								{
									"s3LxAv_48-hover": {
										"data-framer-name": void 0,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-ooms9p"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"dLV9H2uRr"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-e9abed44-df8b-4765-bbfe-7c072006d47b, rgb(0, 0, 0))",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={xrHA2Kp0H}
								variants={{
									"s3LxAv_48-hover": {
										"--extracted-r6o4lv":
											"var(--token-c21010f9-5cb6-4d3d-85fc-4227a6481949, rgb(255, 255, 255))",
									},
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										"s3LxAv_48-hover": {
											children: (
												<React.Fragment>
													<motion.p
														className={"framer-styles-preset-1l7bfec"}
														data-styles-preset={"T3pYYFndi"}
														style={{
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-c21010f9-5cb6-4d3d-85fc-4227a6481949, rgb(255, 255, 255)))",
														}}
													>
														{"Show More"}
													</motion.p>
												</React.Fragment>
											),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-1l7bfec"}
										data-styles-preset={"T3pYYFndi"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-e9abed44-df8b-4765-bbfe-7c072006d47b, rgb(0, 0, 0)))",
										}}
									>
										{"Show More"}
									</motion.p>
								</React.Fragment>
							</RichText>
						</motion.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css5 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-6zg8S.framer-1n96x1o, .framer-6zg8S .framer-1n96x1o { display: block; }",
	".framer-6zg8S.framer-9w2via { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 20px 36px 20px 36px; position: relative; text-decoration: none; width: min-content; }",
	".framer-6zg8S .framer-ooms9p { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-6zg8S.framer-9w2via { gap: 0px; } .framer-6zg8S.framer-9w2via > * { margin: 0px; margin-bottom: calc(10px / 2); margin-top: calc(10px / 2); } .framer-6zg8S.framer-9w2via > :first-child { margin-top: 0px; } .framer-6zg8S.framer-9w2via > :last-child { margin-bottom: 0px; } }",
	...css,
];
var FramerKsAZ0KnKd = withCSS(Component, css5, "framer-6zg8S");
var stdin_default = FramerKsAZ0KnKd;
FramerKsAZ0KnKd.displayName = "Button - Black BG";
FramerKsAZ0KnKd.defaultProps = {
	height: 57.5,
	width: 152.5,
};
addPropertyControls(FramerKsAZ0KnKd, {
	GhxBoxfgA: {
		title: "Cursor",
		type: ControlType.CustomCursor,
	},
	xrHA2Kp0H: {
		defaultValue: "Show More",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	oGjGfyY3A: {
		title: "Link",
		type: ControlType.Link,
	},
	zgrV9HxLK: {
		defaultValue: false,
		title: "New Tab",
		type: ControlType.Boolean,
	},
});
addFonts(
	FramerKsAZ0KnKd,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/rsGe4CHXeARxFZ5mTON5/4FAI0DkDmGYrZt1YoDTf/VY9qRujfw.js
var ButtonBlackBGFonts = getFonts(stdin_default);
var MotionDivWithFX = withFX(motion2.div);
var MotionFooterWithFX = withFX(motion2.footer);
var cycleOrder = ["knE7wtetq", "PZaTJZ3Yh", "jou3BEPQG"];
var serializationHash2 = "framer-cYshH";
var variantClassNames2 = {
	jou3BEPQG: "framer-v-x3s9f",
	knE7wtetq: "framer-v-1d5uo46",
	PZaTJZ3Yh: "framer-v-1idz8mv",
};
function addPropertyOverrides2(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transition12 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var transition2 = {
	delay: 0,
	duration: 1.5,
	ease: [0, 0, 1, 1],
	type: "tween",
};
var animation = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 4.5,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 0,
};
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var humanReadableVariantMap = {
	Desktop: "knE7wtetq",
	Phone: "jou3BEPQG",
	Tablet: "PZaTJZ3Yh",
};
var getProps2 = ({ cursor, height, id, width, ...props }) => {
	var _humanReadableVariantMap_props_variant, _ref;
	return {
		...props,
		SzvBTrBNq: cursor !== null && cursor !== void 0 ? cursor : props.SzvBTrBNq,
		variant:
			(_ref =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref !== void 0
				? _ref
				: "knE7wtetq",
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Variants2 = motion2.create(React2.Fragment);
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo2();
	const {
		style,
		className: className5,
		layoutId,
		variant,
		SzvBTrBNq,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		cycleOrder,
		defaultVariant: "knE7wtetq",
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const sharedStyleClassNames = [className, className3, className2, className4];
	const scopingClassNames = cx2(serializationHash2, ...sharedStyleClassNames);
	const ref1 = React2.useRef(null);
	const router = useRouter();
	const isDisplayed = () => {
		if (baseVariant === "jou3BEPQG") return true;
		return false;
	};
	const defaultLayoutId = React2.useId();
	const componentViewport = useComponentViewport2();
	return (
		<LayoutGroup2
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition12}>
					<MotionFooterWithFX
						{...restProps}
						{...gestureHandlers}
						__framer__styleTransformEffectEnabled={true}
						__framer__transformTargets={[
							{
								target: {
									opacity: 1,
									rotate: 0,
									rotateX: 0,
									rotateY: 0,
									scale: 1,
									skewX: 0,
									skewY: 0,
									x: 0,
									y: -500,
								},
							},
							{
								target: {
									opacity: 1,
									rotate: 0,
									rotateX: 0,
									rotateY: 0,
									scale: 1,
									skewX: 0,
									skewY: 0,
									x: 0,
									y: 0,
								},
							},
						]}
						__framer__transformTrigger={"onInView"}
						__perspectiveFX={false}
						__smartComponentFX={true}
						__targetOpacity={1}
						className={cx2(
							scopingClassNames,
							"framer-1d5uo46",
							className5,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"knE7wtetq"}
						ref={ref !== null && ref !== void 0 ? ref : ref1}
						style={{
							backgroundColor:
								"var(--token-e9abed44-df8b-4765-bbfe-7c072006d47b, rgb(0, 0, 0))",
							...style,
						}}
						{...addPropertyOverrides2(
							{
								jou3BEPQG: {
									"data-framer-name": "Phone",
								},
								PZaTJZ3Yh: {
									"data-framer-name": "Tablet",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion2.div
							className={"framer-p15zb8"}
							data-framer-name={"Container"}
							layoutDependency={layoutDependency}
							layoutId={"v1z_e7q5q"}
						>
							<motion2.div
								className={"framer-5rx6hh"}
								data-framer-name={"Social media"}
								layoutDependency={layoutDependency}
								layoutId={"ENLbMvODc"}
							>
								<RichText2
									__fromCanvasComponent={true}
									className={"framer-1jhrljf"}
									data-framer-cursor={SzvBTrBNq}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"Q1HcnSQ8s"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-c21010f9-5cb6-4d3d-85fc-4227a6481949, rgb(255, 255, 255))",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React2.Fragment>
										<motion2.p
											className={"framer-styles-preset-1l7bfec"}
											data-styles-preset={"T3pYYFndi"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-c21010f9-5cb6-4d3d-85fc-4227a6481949, rgb(255, 255, 255)))",
											}}
										>
											<Link2
												href={"https://linkedin.com/in/peteryelton"}
												nodeId={"Q1HcnSQ8s"}
												openInNewTab={true}
												smoothScroll={false}
											>
												<motion2.a
													className={"framer-styles-preset-dsdgjd"}
													data-styles-preset={"o1DydXi3K"}
												>
													{"Linkedin"}
												</motion2.a>
											</Link2>
										</motion2.p>
									</React2.Fragment>
								</RichText2>
								<RichText2
									__fromCanvasComponent={true}
									className={"framer-1tscxa2"}
									data-framer-cursor={SzvBTrBNq}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"MhcEAEylX"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-c21010f9-5cb6-4d3d-85fc-4227a6481949, rgb(255, 255, 255))",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React2.Fragment>
										<motion2.p
											className={"framer-styles-preset-1l7bfec"}
											data-styles-preset={"T3pYYFndi"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-c21010f9-5cb6-4d3d-85fc-4227a6481949, rgb(255, 255, 255)))",
											}}
										>
											<Link2
												href={"https://github.com/rknm-cell"}
												nodeId={"MhcEAEylX"}
												openInNewTab={true}
												smoothScroll={false}
											>
												<motion2.a
													className={"framer-styles-preset-dsdgjd"}
													data-styles-preset={"o1DydXi3K"}
												>
													{"GitHub"}
												</motion2.a>
											</Link2>
										</motion2.p>
									</React2.Fragment>
								</RichText2>
								<RichText2
									__fromCanvasComponent={true}
									className={"framer-1aj6f0t"}
									data-framer-cursor={SzvBTrBNq}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"XBtfnkcz4"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-c21010f9-5cb6-4d3d-85fc-4227a6481949, rgb(255, 255, 255))",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React2.Fragment>
										<motion2.p
											className={"framer-styles-preset-1l7bfec"}
											data-styles-preset={"T3pYYFndi"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-c21010f9-5cb6-4d3d-85fc-4227a6481949, rgb(255, 255, 255)))",
											}}
										>
											<Link2
												href={"mailto:peteryelton@gmail.com"}
												nodeId={"XBtfnkcz4"}
												openInNewTab={true}
												smoothScroll={false}
											>
												<motion2.a
													className={"framer-styles-preset-dsdgjd"}
													data-styles-preset={"o1DydXi3K"}
												>
													{"Email"}
												</motion2.a>
											</Link2>
										</motion2.p>
									</React2.Fragment>
								</RichText2>
							</motion2.div>
							<motion2.div
								className={"framer-1i0y87o"}
								data-framer-name={"CTA Text"}
								layoutDependency={layoutDependency}
								layoutId={"PSp0LlZUL"}
							>
								<motion2.div
									className={"framer-1gipt2o"}
									data-framer-name={"Text"}
									layoutDependency={layoutDependency}
									layoutId={"Cam1VFeiJ"}
								>
									<RichText2
										__fromCanvasComponent={true}
										className={"framer-8ae4p0"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"gweMCe4SI"}
										style={{
											"--extracted-1eung3n": "rgb(255, 255, 255)",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
										{...addPropertyOverrides2(
											{
												jou3BEPQG: {
													children: (
														<React2.Fragment>
															<motion2.h4
																className={"framer-styles-preset-v5rub6"}
																data-styles-preset={"CDJ_2sb5e"}
																style={{
																	"--framer-text-alignment": "left",
																	"--framer-text-color":
																		"var(--extracted-1eung3n, rgb(255, 255, 255))",
																}}
															>
																<motion2.span
																	data-text-fill={"true"}
																	style={{
																		backgroundImage:
																			"linear-gradient(95deg, rgb(255, 255, 255) 37%, rgb(56, 56, 56) 95%)",
																	}}
																>
																	{
																		"Curious about what we can create together? "
																	}
																	<motion2.br />
																	{
																		"Let\u2019s bring something extraordinary to life!"
																	}
																</motion2.span>
															</motion2.h4>
														</React2.Fragment>
													),
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<React2.Fragment>
											<motion2.h4
												className={"framer-styles-preset-v5rub6"}
												data-styles-preset={"CDJ_2sb5e"}
												style={{
													"--framer-text-color":
														"var(--extracted-1eung3n, rgb(255, 255, 255))",
												}}
											>
												<motion2.span
													data-text-fill={"true"}
													style={{
														backgroundImage:
															"linear-gradient(95deg, rgb(255, 255, 255) 37%, rgb(56, 56, 56) 95%)",
													}}
												>
													{"Curious about what we can create together? "}
													<motion2.br />
													{"Let\u2019s bring something extraordinary to life!"}
												</motion2.span>
											</motion2.h4>
										</React2.Fragment>
									</RichText2>
								</motion2.div>
								<motion2.div
									className={"framer-114cw9p"}
									data-framer-name={"CTA"}
									layoutDependency={layoutDependency}
									layoutId={"pabM1IrpN"}
								>
									<ResolveLinks
										links={[
											{
												href: {
													webPageId: "BUkPVXyp3",
												},
												implicitPathVariables: void 0,
											},
											{
												href: {
													webPageId: "BUkPVXyp3",
												},
												implicitPathVariables: void 0,
											},
											{
												href: {
													webPageId: "BUkPVXyp3",
												},
												implicitPathVariables: void 0,
											},
										]}
									>
										{(resolvedLinks) => (
											<ComponentViewportProvider
												height={57}
												y={
													((componentViewport === null ||
													componentViewport === void 0
														? void 0
														: componentViewport.y) || 0) +
													0 +
													((((componentViewport === null ||
													componentViewport === void 0
														? void 0
														: componentViewport.height) || 800) -
														0 -
														1e3) /
														2 +
														0 +
														0) +
													60 +
													345.90000000000003 +
													0 +
													97.6 +
													0
												}
												{...addPropertyOverrides2(
													{
														jou3BEPQG: {
															width: `min(${(componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.width) || "100vw"} - 40px, 1600px)`,
															y:
																((componentViewport === null ||
																componentViewport === void 0
																	? void 0
																	: componentViewport.y) || 0) +
																0 +
																(((componentViewport === null ||
																componentViewport === void 0
																	? void 0
																	: componentViewport.height) || 936) -
																	0 -
																	1e3 +
																	0 +
																	0) +
																140 +
																257.8 +
																0 +
																89.6 +
																0 +
																65.6,
														},
													},
													baseVariant,
													gestureVariant,
												)}
											>
												<motion2.div
													className={"framer-18ylq97-container"}
													layoutDependency={layoutDependency}
													layoutId={"WYPdsUutX-container"}
												>
													{_jsx2(stdin_default, {
														GhxBoxfgA: SzvBTrBNq,
														height: "100%",
														id: "WYPdsUutX",
														layoutId: "WYPdsUutX",
														oGjGfyY3A: resolvedLinks[0],
														width: "100%",
														xrHA2Kp0H: "Get in Touch",
														zgrV9HxLK: false,
														...addPropertyOverrides2(
															{
																jou3BEPQG: {
																	oGjGfyY3A: resolvedLinks[2],
																	style: {
																		width: "100%",
																	},
																},
																PZaTJZ3Yh: {
																	oGjGfyY3A: resolvedLinks[1],
																},
															},
															baseVariant,
															gestureVariant,
														),
													})}
												</motion2.div>
											</ComponentViewportProvider>
										)}
									</ResolveLinks>
									<motion2.div
										className={"framer-1qm2cy6"}
										data-framer-name={"Available"}
										layoutDependency={layoutDependency}
										layoutId={"ylhKhyiP7"}
									>
										<motion2.div
											className={"framer-1t3guf3"}
											data-framer-name={"Pulse"}
											layoutDependency={layoutDependency}
											layoutId={"VEZulTrd6"}
										>
											<motion2.div
												className={"framer-wp73wb"}
												data-framer-name={"Small"}
												layoutDependency={layoutDependency}
												layoutId={"IOsQ3bWTc"}
												style={{
													backgroundColor:
														"var(--token-c21010f9-5cb6-4d3d-85fc-4227a6481949, rgb(255, 255, 255))",
													borderBottomLeftRadius: 20,
													borderBottomRightRadius: 20,
													borderTopLeftRadius: 20,
													borderTopRightRadius: 20,
												}}
											/>
											<MotionDivWithFX
												__framer__loop={animation}
												__framer__loopEffectEnabled={true}
												__framer__loopRepeatDelay={0}
												__framer__loopRepeatType={"loop"}
												__framer__loopTransition={transition2}
												__perspectiveFX={false}
												__smartComponentFX={true}
												__targetOpacity={1}
												className={"framer-nwaviv"}
												data-framer-name={"Big"}
												layoutDependency={layoutDependency}
												layoutId={"k4nYUD4IY"}
												style={{
													backgroundColor:
														"var(--token-c21010f9-5cb6-4d3d-85fc-4227a6481949, rgb(255, 255, 255))",
													borderBottomLeftRadius: 20,
													borderBottomRightRadius: 20,
													borderTopLeftRadius: 20,
													borderTopRightRadius: 20,
												}}
											/>
										</motion2.div>
										<RichText2
											__fromCanvasComponent={true}
											className={"framer-18yekuq"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"qkStH1BcR"}
											style={{
												"--extracted-r6o4lv":
													"var(--token-c21010f9-5cb6-4d3d-85fc-4227a6481949, rgb(255, 255, 255))",
												"--framer-link-text-color": "rgb(0, 153, 255)",
												"--framer-link-text-decoration": "underline",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React2.Fragment>
												<motion2.p
													className={"framer-styles-preset-124zfba"}
													data-styles-preset={"uKaW9yEJh"}
													style={{
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-c21010f9-5cb6-4d3d-85fc-4227a6481949, rgb(255, 255, 255)))",
													}}
												>
													{"Available For Work"}
												</motion2.p>
											</React2.Fragment>
										</RichText2>
									</motion2.div>
								</motion2.div>
							</motion2.div>
							<motion2.div
								className={"framer-19yxqdg"}
								data-framer-name={"Footer detail"}
								layoutDependency={layoutDependency}
								layoutId={"hcUsP7V5J"}
							>
								<motion2.div
									className={"framer-xqh94c"}
									data-framer-name={"Info"}
									layoutDependency={layoutDependency}
									layoutId={"k9ep_xAFN"}
								>
									<RichText2
										__fromCanvasComponent={true}
										className={"framer-158rlxh"}
										data-framer-cursor={SzvBTrBNq}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"x85B3XL3c"}
										style={{
											"--extracted-2gxw0f":
												"var(--token-c21010f9-5cb6-4d3d-85fc-4227a6481949, rgb(255, 255, 255))",
											"--extracted-r6o4lv":
												"var(--token-c21010f9-5cb6-4d3d-85fc-4227a6481949, rgb(255, 255, 255))",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
										{...addPropertyOverrides2(
											{
												jou3BEPQG: {
													children: (
														<React2.Fragment>
															<motion2.p
																className={"framer-styles-preset-124zfba"}
																data-styles-preset={"uKaW9yEJh"}
																style={{
																	"--framer-text-alignment": "left",
																	"--framer-text-color":
																		"var(--extracted-r6o4lv, var(--token-c21010f9-5cb6-4d3d-85fc-4227a6481949, rgb(255, 255, 255)))",
																}}
															>
																<Link2
																	href={"mailto:peteryelton@gmail.com"}
																	nodeId={"x85B3XL3c"}
																	openInNewTab={true}
																	smoothScroll={false}
																>
																	<motion2.a
																		className={"framer-styles-preset-dsdgjd"}
																		data-styles-preset={"o1DydXi3K"}
																	>
																		{"peteryelton@gmail.com"}
																	</motion2.a>
																</Link2>
															</motion2.p>
															<motion2.p
																className={"framer-styles-preset-124zfba"}
																data-styles-preset={"uKaW9yEJh"}
																style={{
																	"--framer-text-alignment": "left",
																	"--framer-text-color":
																		"var(--extracted-2gxw0f, var(--token-c21010f9-5cb6-4d3d-85fc-4227a6481949, rgb(255, 255, 255)))",
																}}
															>
																<Link2
																	href={"https://github.com/rknm-cell"}
																	nodeId={"x85B3XL3c"}
																	openInNewTab={true}
																	smoothScroll={false}
																>
																	<motion2.a
																		className={"framer-styles-preset-dsdgjd"}
																		data-styles-preset={"o1DydXi3K"}
																	>
																		{"GitHub"}
																	</motion2.a>
																</Link2>
															</motion2.p>
														</React2.Fragment>
													),
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<React2.Fragment>
											<motion2.p
												className={"framer-styles-preset-124zfba"}
												data-styles-preset={"uKaW9yEJh"}
												style={{
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-c21010f9-5cb6-4d3d-85fc-4227a6481949, rgb(255, 255, 255)))",
												}}
											>
												<Link2
													href={"mailto:peteryelton@gmail.com"}
													nodeId={"x85B3XL3c"}
													openInNewTab={true}
													smoothScroll={false}
												>
													<motion2.a
														className={"framer-styles-preset-dsdgjd"}
														data-styles-preset={"o1DydXi3K"}
													>
														{"peteryelton@gmail.com"}
													</motion2.a>
												</Link2>
											</motion2.p>
											<motion2.p
												className={"framer-styles-preset-124zfba"}
												data-styles-preset={"uKaW9yEJh"}
												style={{
													"--framer-text-color":
														"var(--extracted-2gxw0f, var(--token-c21010f9-5cb6-4d3d-85fc-4227a6481949, rgb(255, 255, 255)))",
												}}
											>
												<Link2
													href={"https://github.com/rknm-cell"}
													nodeId={"x85B3XL3c"}
													openInNewTab={true}
													smoothScroll={false}
												>
													<motion2.a
														className={"framer-styles-preset-dsdgjd"}
														data-styles-preset={"o1DydXi3K"}
													>
														{"GitHub"}
													</motion2.a>
												</Link2>
											</motion2.p>
										</React2.Fragment>
									</RichText2>
									<RichText2
										__fromCanvasComponent={true}
										className={"framer-4awl5x"}
										data-framer-cursor={SzvBTrBNq}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"XsmFFISoA"}
										style={{
											"--extracted-2gxw0f":
												"var(--token-c21010f9-5cb6-4d3d-85fc-4227a6481949, rgb(255, 255, 255))",
											"--extracted-r6o4lv":
												"var(--token-c21010f9-5cb6-4d3d-85fc-4227a6481949, rgb(255, 255, 255))",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
										{...addPropertyOverrides2(
											{
												jou3BEPQG: {
													children: (
														<React2.Fragment>
															<motion2.p
																className={"framer-styles-preset-124zfba"}
																data-styles-preset={"uKaW9yEJh"}
																style={{
																	"--framer-text-alignment": "left",
																	"--framer-text-color":
																		"var(--extracted-r6o4lv, var(--token-c21010f9-5cb6-4d3d-85fc-4227a6481949, rgb(255, 255, 255)))",
																}}
															>
																{"Designed & Developed"}
															</motion2.p>
															<motion2.p
																className={"framer-styles-preset-124zfba"}
																data-styles-preset={"uKaW9yEJh"}
																style={{
																	"--framer-text-alignment": "left",
																	"--framer-text-color":
																		"var(--extracted-2gxw0f, var(--token-c21010f9-5cb6-4d3d-85fc-4227a6481949, rgb(255, 255, 255)))",
																}}
															>
																{"by "}
																<Link2
																	href={
																		"https://contra.com/peterhodak/services"
																	}
																	nodeId={"XsmFFISoA"}
																	openInNewTab={true}
																	smoothScroll={false}
																>
																	<motion2.a
																		className={"framer-styles-preset-dsdgjd"}
																		data-styles-preset={"o1DydXi3K"}
																	>
																		{"Peter Yelton"}
																	</motion2.a>
																</Link2>
															</motion2.p>
														</React2.Fragment>
													),
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<React2.Fragment>
											<motion2.p
												className={"framer-styles-preset-124zfba"}
												data-styles-preset={"uKaW9yEJh"}
												style={{
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-c21010f9-5cb6-4d3d-85fc-4227a6481949, rgb(255, 255, 255)))",
												}}
											>
												{"Designed & Developed"}
											</motion2.p>
											<motion2.p
												className={"framer-styles-preset-124zfba"}
												data-styles-preset={"uKaW9yEJh"}
												style={{
													"--framer-text-color":
														"var(--extracted-2gxw0f, var(--token-c21010f9-5cb6-4d3d-85fc-4227a6481949, rgb(255, 255, 255)))",
												}}
											>
												{"by "}
												<Link2
													href={"https://github.com/rknm-cell"}
													nodeId={"XsmFFISoA"}
													openInNewTab={true}
													smoothScroll={false}
												>
													<motion2.a
														className={"framer-styles-preset-dsdgjd"}
														data-styles-preset={"o1DydXi3K"}
													>
														{"Peter Yelton"}
													</motion2.a>
												</Link2>
											</motion2.p>
										</React2.Fragment>
									</RichText2>
								</motion2.div>
								<RichText2
									__fromCanvasComponent={true}
									className={"framer-frly03"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"K254_p2dy"}
									style={{
										"--extracted-2gxw0f":
											"var(--token-c21010f9-5cb6-4d3d-85fc-4227a6481949, rgb(255, 255, 255))",
										"--extracted-r6o4lv":
											"var(--token-c21010f9-5cb6-4d3d-85fc-4227a6481949, rgb(255, 255, 255))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									variants={{
										jou3BEPQG: {
											"--extracted-r6o4lv": "rgb(255, 255, 255)",
										},
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides2(
										{
											jou3BEPQG: {
												children: (
													<React2.Fragment>
														<motion2.p
															className={"framer-styles-preset-124zfba"}
															data-styles-preset={"uKaW9yEJh"}
															style={{
																"--framer-text-alignment": "center",
																"--framer-text-color":
																	"var(--extracted-r6o4lv, rgb(255, 255, 255))",
															}}
														>
															{"All rights reserved, Peter Yelton \xA92026"}
														</motion2.p>
													</React2.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React2.Fragment>
										<motion2.p
											className={"framer-styles-preset-124zfba"}
											data-styles-preset={"uKaW9yEJh"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-c21010f9-5cb6-4d3d-85fc-4227a6481949, rgb(255, 255, 255)))",
											}}
										>
											{"All rights reserved,"}
										</motion2.p>
										<motion2.p
											className={"framer-styles-preset-124zfba"}
											data-styles-preset={"uKaW9yEJh"}
											style={{
												"--framer-text-color":
													"var(--extracted-2gxw0f, var(--token-c21010f9-5cb6-4d3d-85fc-4227a6481949, rgb(255, 255, 255)))",
											}}
										>
											{"Peter Yelton \xA92026"}
										</motion2.p>
									</React2.Fragment>
								</RichText2>
								{isDisplayed() && (
									<motion2.div
										className={"framer-auam3w"}
										layoutDependency={layoutDependency}
										layoutId={"jHDYov_2N"}
										style={{
											backgroundColor: "rgb(38, 38, 38)",
										}}
									/>
								)}
							</motion2.div>
						</motion2.div>
					</MotionFooterWithFX>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css6 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-cYshH.framer-p1j7fe, .framer-cYshH .framer-p1j7fe { display: block; }",
	".framer-cYshH.framer-1d5uo46 { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: hidden; padding: 0px 80px 0px 80px; position: relative; width: 1200px; }",
	".framer-cYshH .framer-p15zb8 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; height: calc(var(--framer-viewport-height, 100vh) * 1); justify-content: space-between; max-width: 1600px; overflow: hidden; padding: 60px 0px 60px 0px; position: relative; width: 100%; }",
	".framer-cYshH .framer-5rx6hh { align-content: flex-end; align-items: flex-end; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 26px; height: min-content; justify-content: flex-end; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-cYshH .framer-1jhrljf, .framer-cYshH .framer-1tscxa2, .framer-cYshH .framer-1aj6f0t, .framer-cYshH .framer-18yekuq, .framer-cYshH .framer-158rlxh, .framer-cYshH .framer-4awl5x, .framer-cYshH .framer-frly03 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-cYshH .framer-1i0y87o { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 40px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-cYshH .framer-1gipt2o { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-cYshH .framer-8ae4p0 { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-cYshH .framer-114cw9p { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 40px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-cYshH .framer-18ylq97-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-cYshH .framer-1qm2cy6 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-cYshH .framer-1t3guf3 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-cYshH .framer-wp73wb { flex: none; height: 10px; overflow: hidden; position: relative; width: 10px; will-change: var(--framer-will-change-override, transform); }",
	".framer-cYshH .framer-nwaviv { bottom: 0px; flex: none; overflow: hidden; position: absolute; right: 0px; top: 0px; width: 10px; will-change: var(--framer-will-change-override, transform); z-index: 1; }",
	".framer-cYshH .framer-19yxqdg { align-content: flex-end; align-items: flex-end; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-cYshH .framer-xqh94c { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 170px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-cYshH .framer-auam3w { flex: none; height: 1px; overflow: visible; position: relative; width: 350px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-cYshH.framer-1d5uo46, .framer-cYshH .framer-5rx6hh, .framer-cYshH .framer-1i0y87o, .framer-cYshH .framer-114cw9p, .framer-cYshH .framer-1qm2cy6, .framer-cYshH .framer-1t3guf3, .framer-cYshH .framer-xqh94c { gap: 0px; } .framer-cYshH.framer-1d5uo46 > * { margin: 0px; margin-bottom: calc(0px / 2); margin-top: calc(0px / 2); } .framer-cYshH.framer-1d5uo46 > :first-child, .framer-cYshH .framer-1i0y87o > :first-child { margin-top: 0px; } .framer-cYshH.framer-1d5uo46 > :last-child, .framer-cYshH .framer-1i0y87o > :last-child { margin-bottom: 0px; } .framer-cYshH .framer-5rx6hh > * { margin: 0px; margin-left: calc(26px / 2); margin-right: calc(26px / 2); } .framer-cYshH .framer-5rx6hh > :first-child, .framer-cYshH .framer-114cw9p > :first-child, .framer-cYshH .framer-1qm2cy6 > :first-child, .framer-cYshH .framer-1t3guf3 > :first-child, .framer-cYshH .framer-xqh94c > :first-child { margin-left: 0px; } .framer-cYshH .framer-5rx6hh > :last-child, .framer-cYshH .framer-114cw9p > :last-child, .framer-cYshH .framer-1qm2cy6 > :last-child, .framer-cYshH .framer-1t3guf3 > :last-child, .framer-cYshH .framer-xqh94c > :last-child { margin-right: 0px; } .framer-cYshH .framer-1i0y87o > * { margin: 0px; margin-bottom: calc(40px / 2); margin-top: calc(40px / 2); } .framer-cYshH .framer-114cw9p > * { margin: 0px; margin-left: calc(40px / 2); margin-right: calc(40px / 2); } .framer-cYshH .framer-1qm2cy6 > * { margin: 0px; margin-left: calc(16px / 2); margin-right: calc(16px / 2); } .framer-cYshH .framer-1t3guf3 > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-cYshH .framer-xqh94c > * { margin: 0px; margin-left: calc(170px / 2); margin-right: calc(170px / 2); } }",
	".framer-cYshH.framer-v-1idz8mv.framer-1d5uo46 { padding: 0px 30px 0px 30px; width: 810px; }",
	".framer-cYshH.framer-v-x3s9f.framer-1d5uo46 { justify-content: flex-end; padding: 0px 20px 0px 20px; width: 390px; }",
	".framer-cYshH.framer-v-x3s9f .framer-p15zb8 { padding: 140px 0px 24px 0px; }",
	".framer-cYshH.framer-v-x3s9f .framer-5rx6hh { gap: 30px; justify-content: flex-start; }",
	".framer-cYshH.framer-v-x3s9f .framer-1i0y87o { gap: 32px; }",
	".framer-cYshH.framer-v-x3s9f .framer-114cw9p { align-content: flex-start; align-items: flex-start; flex-direction: column; overflow: visible; }",
	".framer-cYshH.framer-v-x3s9f .framer-18ylq97-container { order: 1; width: 100%; }",
	".framer-cYshH.framer-v-x3s9f .framer-1qm2cy6 { order: 0; padding: 0px 0px 0px 14px; }",
	".framer-cYshH.framer-v-x3s9f .framer-19yxqdg { align-content: center; align-items: center; flex-direction: column; gap: 24px; justify-content: flex-start; }",
	".framer-cYshH.framer-v-x3s9f .framer-xqh94c { flex: none; gap: unset; justify-content: space-between; order: 0; width: 100%; }",
	".framer-cYshH.framer-v-x3s9f .framer-frly03 { order: 2; }",
	".framer-cYshH.framer-v-x3s9f .framer-auam3w { order: 1; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-cYshH.framer-v-x3s9f .framer-5rx6hh, .framer-cYshH.framer-v-x3s9f .framer-1i0y87o, .framer-cYshH.framer-v-x3s9f .framer-114cw9p, .framer-cYshH.framer-v-x3s9f .framer-19yxqdg, .framer-cYshH.framer-v-x3s9f .framer-xqh94c { gap: 0px; } .framer-cYshH.framer-v-x3s9f .framer-5rx6hh > * { margin: 0px; margin-left: calc(30px / 2); margin-right: calc(30px / 2); } .framer-cYshH.framer-v-x3s9f .framer-5rx6hh > :first-child { margin-left: 0px; } .framer-cYshH.framer-v-x3s9f .framer-5rx6hh > :last-child { margin-right: 0px; } .framer-cYshH.framer-v-x3s9f .framer-1i0y87o > * { margin: 0px; margin-bottom: calc(32px / 2); margin-top: calc(32px / 2); } .framer-cYshH.framer-v-x3s9f .framer-1i0y87o > :first-child, .framer-cYshH.framer-v-x3s9f .framer-114cw9p > :first-child, .framer-cYshH.framer-v-x3s9f .framer-19yxqdg > :first-child { margin-top: 0px; } .framer-cYshH.framer-v-x3s9f .framer-1i0y87o > :last-child, .framer-cYshH.framer-v-x3s9f .framer-114cw9p > :last-child, .framer-cYshH.framer-v-x3s9f .framer-19yxqdg > :last-child { margin-bottom: 0px; } .framer-cYshH.framer-v-x3s9f .framer-114cw9p > * { margin: 0px; margin-bottom: calc(40px / 2); margin-top: calc(40px / 2); } .framer-cYshH.framer-v-x3s9f .framer-19yxqdg > * { margin: 0px; margin-bottom: calc(24px / 2); margin-top: calc(24px / 2); } .framer-cYshH.framer-v-x3s9f .framer-xqh94c > *, .framer-cYshH.framer-v-x3s9f .framer-xqh94c > :first-child, .framer-cYshH.framer-v-x3s9f .framer-xqh94c > :last-child { margin: 0px; } }",
	...css,
	...css3,
	...css2,
	...css4,
];
var FramerVY9qRujfw = withCSS2(Component2, css6, "framer-cYshH");
var stdin_default2 = FramerVY9qRujfw;
FramerVY9qRujfw.displayName = "Footer";
FramerVY9qRujfw.defaultProps = {
	height: 800,
	width: 1200,
};
addPropertyControls2(FramerVY9qRujfw, {
	variant: {
		options: ["knE7wtetq", "PZaTJZ3Yh", "jou3BEPQG"],
		optionTitles: ["Desktop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType2.Enum,
	},
	SzvBTrBNq: {
		title: "Cursor",
		type: ControlType2.CustomCursor,
	},
});
addFonts2(
	FramerVY9qRujfw,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...ButtonBlackBGFonts,
		...getFontsFromSharedStyle2(fonts),
		...getFontsFromSharedStyle2(fonts3),
		...getFontsFromSharedStyle2(fonts2),
		...getFontsFromSharedStyle2(fonts4),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:footer
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "jou3BEPQG",
	md: "PZaTJZ3Yh",
	xl: "knE7wtetq",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"b917fc1195920e6c8a50255315bde13451700c9dc2ee3323349c54f78331e19f"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders FooterFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"b917fc1195920e6c8a50255315bde13451700c9dc2ee3323349c54f78331e19f"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var footer_default = ComponentWithRoot;
export { footer_default as default };
