// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project b917fc1195920e6c "Portfolio", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop - Close' | 'Desktop - Open' | 'Tablet - Close' | 'Tablet - Open' | 'Mobile - Close' | 'Mobile - Open' // Variant
 * cursor?: undefined // Cursor
}} Props

 */
import { stdin_default as stdin_default2 } from "./chunks/chunk-XXTIMTQJ.js";
import { stdin_default } from "./chunks/chunk-S5YRG7ET.js";
import { routes } from "./chunks/chunk-MBSQQC4T.js";

// virtual:navigation
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/dVoAulXRIIfnaJi48vnL/Aeu6q4BNmOPneV93KC9Q/x8X7x6HpE.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	Link,
	RichText,
	SmartComponentScopedContainer,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var MenuFonts = getFonts(stdin_default);
var MenuButtonFonts = getFonts(stdin_default2);
var cycleOrder = [
	"ttIMsCdGf",
	"YxAczhV6j",
	"bNJrsTReY",
	"rqjaZSxtJ",
	"ANBzqZO9P",
	"lOX7ou7Ng",
];
var serializationHash = "framer-B7oPy";
var variantClassNames = {
	ANBzqZO9P: "framer-v-1lzp3ub",
	bNJrsTReY: "framer-v-ode4tf",
	lOX7ou7Ng: "framer-v-1xhzf5f",
	rqjaZSxtJ: "framer-v-1c5dtbo",
	ttIMsCdGf: "framer-v-14x3d1s",
	YxAczhV6j: "framer-v-16lolzi",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var transition2 = {
	delay: 0,
	duration: 0.5,
	ease: [0.49, -0.01, 0, 1],
	type: "tween",
};
var transition3 = {
	delay: 0,
	duration: 1,
	ease: [0.85, 0, 0.7, 0.77],
	type: "tween",
};
var matchVariant = (...args) => {
	for (const arg of args) {
		if (arg && typeof arg === "string") return arg;
	}
	return void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Desktop - Close": "ttIMsCdGf",
	"Desktop - Open": "YxAczhV6j",
	"Mobile - Close": "ANBzqZO9P",
	"Mobile - Open": "lOX7ou7Ng",
	"Tablet - Close": "bNJrsTReY",
	"Tablet - Open": "rqjaZSxtJ",
};
var getProps = ({ cursor, height, id, width, ...props }) => {
	return {
		...props,
		Miu51ahMm: cursor ?? props.Miu51ahMm,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "ttIMsCdGf",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className,
		layoutId,
		variant,
		Miu51ahMm: Miu51ahMm2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "ttIMsCdGf",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const cUVYJiXkH1lfw7uz = activeVariantCallback(async (...args) => {
		setVariant("YxAczhV6j");
	});
	const cUVYJiXkH181hn5i = activeVariantCallback(async (...args) => {
		setVariant("ttIMsCdGf");
	});
	const cUVYJiXkH1e1ed5g = activeVariantCallback(async (...args) => {
		setVariant("rqjaZSxtJ");
	});
	const cUVYJiXkH183yufw = activeVariantCallback(async (...args) => {
		setVariant("bNJrsTReY");
	});
	const cUVYJiXkH18tcpjb = activeVariantCallback(async (...args) => {
		setVariant("lOX7ou7Ng");
	});
	const cUVYJiXkHt55j48 = activeVariantCallback(async (...args) => {
		setVariant("ANBzqZO9P");
	});
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (["ANBzqZO9P", "lOX7ou7Ng"].includes(baseVariant)) return false;
		return true;
	};
	const isDisplayed1 = () => {
		if (baseVariant === "lOX7ou7Ng") return true;
		return false;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition
					value={transition1}
					{...addPropertyOverrides(
						{
							ANBzqZO9P: {
								value: transition2,
							},
							lOX7ou7Ng: {
								value: transition3,
							},
						},
						baseVariant,
						gestureVariant,
					)}
				>
					<motion.header
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-14x3d1s",
							className,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Desktop - Close"}
						layoutDependency={layoutDependency}
						layoutId={"ttIMsCdGf"}
						ref={refBinding}
						style={{
							"--border-bottom-width": "1px",
							"--border-color":
								"var(--token-041fe102-52af-45fc-9163-7f47a549ff42, rgb(245, 245, 245))",
							"--border-left-width": "0px",
							"--border-right-width": "0px",
							"--border-style": "solid",
							"--border-top-width": "0px",
							backgroundColor:
								"var(--token-c21010f9-5cb6-4d3d-85fc-4227a6481949, rgb(255, 255, 255))",
							...style,
						}}
						{...addPropertyOverrides(
							{
								ANBzqZO9P: {
									"data-framer-name": "Mobile - Close",
								},
								bNJrsTReY: {
									"data-framer-name": "Tablet - Close",
								},
								lOX7ou7Ng: {
									"data-framer-name": "Mobile - Open",
								},
								rqjaZSxtJ: {
									"data-framer-name": "Tablet - Open",
								},
								YxAczhV6j: {
									"data-framer-name": "Desktop - Open",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-fpkjic"}
							data-framer-name={"Container"}
							layoutDependency={layoutDependency}
							layoutId={"OWRyPguf4"}
						>
							<Link
								href={{
									webPageId: "augiA20Il",
								}}
								motionChild={true}
								nodeId={"qGoHRPoRe"}
								scopeId={"x8X7x6HpE"}
							>
								<motion.a
									className={"framer-1iby9z9 framer-zagk1c"}
									data-framer-cursor={Miu51ahMm2}
									data-framer-name={"Logo"}
									layoutDependency={layoutDependency}
									layoutId={"qGoHRPoRe"}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-89dhfu"}
										fonts={["Inter-Bold"]}
										layoutDependency={layoutDependency}
										layoutId={"hevleMcN2"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-e9abed44-df8b-4765-bbfe-7c072006d47b, rgb(0, 0, 0))",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												dir={"auto"}
												style={{
													"--font-selector": "SW50ZXItQm9sZA==",
													"--framer-font-size": "30px",
													"--framer-font-weight": "700",
													"--framer-letter-spacing": "-0.06em",
													"--framer-line-height": "1.1em",
													"--framer-text-alignment": "justify",
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-e9abed44-df8b-4765-bbfe-7c072006d47b, rgb(0, 0, 0)))",
												}}
											>
												{"PETER"}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.a>
							</Link>
							<motion.div
								className={"framer-e4ig5p"}
								data-framer-name={"Desktop Menu"}
								layoutDependency={layoutDependency}
								layoutId={"DbWx2peMV"}
							>
								{isDisplayed() && (
									<ComponentViewportProvider
										height={20}
										y={(componentViewport?.y || 0) + 30 + 0 + 6.5 + 0}
										{...addPropertyOverrides(
											{
												bNJrsTReY: {
													y: (componentViewport?.y || 0) + 24 + 0 + 6.5 + 0,
												},
												rqjaZSxtJ: {
													y: (componentViewport?.y || 0) + 24 + 0 + 6.5 + 0,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainer
											className={"framer-102v5yv-container"}
											layoutDependency={layoutDependency}
											layoutId={"yMYY0btyH-container"}
											nodeId={"yMYY0btyH"}
											rendersWithMotion={true}
											scopeId={"x8X7x6HpE"}
											style={{
												opacity: 0,
											}}
											variants={{
												rqjaZSxtJ: {
													opacity: 1,
												},
												YxAczhV6j: {
													opacity: 1,
												},
											}}
										>
											{_jsx(stdin_default, {
												height: "100%",
												id: "yMYY0btyH",
												layoutId: "yMYY0btyH",
												variant: matchVariant("B8Rx8xzvZ"),
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								)}
								<ComponentViewportProvider
									height={18}
									width={"18px"}
									y={(componentViewport?.y || 0) + 30 + 0 + 6.5 + 1}
									{...addPropertyOverrides(
										{
											ANBzqZO9P: {
												y: (componentViewport?.y || 0) + 20 + 0 + 7.5 + 0,
											},
											bNJrsTReY: {
												y: (componentViewport?.y || 0) + 24 + 0 + 6.5 + 1,
											},
											lOX7ou7Ng: {
												y: (componentViewport?.y || 0) + 20 + 0 + 7.5 + 0,
											},
											rqjaZSxtJ: {
												y: (componentViewport?.y || 0) + 24 + 0 + 6.5 + 1,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainer
										className={"framer-1hsaif8-container"}
										layoutDependency={layoutDependency}
										layoutId={"cQUX9Qs5x-container"}
										nodeId={"cQUX9Qs5x"}
										rendersWithMotion={true}
										scopeId={"x8X7x6HpE"}
									>
										{_jsx(stdin_default2, {
											cUVYJiXkH: cUVYJiXkH1lfw7uz,
											height: "100%",
											id: "cQUX9Qs5x",
											kHmT162pD: Miu51ahMm2,
											layoutId: "cQUX9Qs5x",
											style: {
												height: "100%",
												width: "100%",
											},
											variant: matchVariant("bFHeAna5r"),
											width: "100%",
											...addPropertyOverrides(
												{
													ANBzqZO9P: {
														cUVYJiXkH: cUVYJiXkH18tcpjb,
													},
													bNJrsTReY: {
														cUVYJiXkH: cUVYJiXkH1e1ed5g,
													},
													lOX7ou7Ng: {
														cUVYJiXkH: cUVYJiXkHt55j48,
													},
													rqjaZSxtJ: {
														cUVYJiXkH: cUVYJiXkH183yufw,
													},
													YxAczhV6j: {
														cUVYJiXkH: cUVYJiXkH181hn5i,
													},
												},
												baseVariant,
												gestureVariant,
											),
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							</motion.div>
						</motion.div>
						{isDisplayed1() && (
							<motion.div
								className={"framer-ddqdi5"}
								data-framer-name={"Mobile Menu"}
								layoutDependency={layoutDependency}
								layoutId={"cBqjTRNvl"}
							>
								<ComponentViewportProvider
									height={20}
									{...addPropertyOverrides(
										{
											lOX7ou7Ng: {
												y: (componentViewport?.y || 0) + 20 + 33 + 400,
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<SmartComponentScopedContainer
										className={"framer-16qi4b4-container"}
										layoutDependency={layoutDependency}
										layoutId={"fDBvepaDX-container"}
										nodeId={"fDBvepaDX"}
										rendersWithMotion={true}
										scopeId={"x8X7x6HpE"}
									>
										{_jsx(stdin_default, {
											height: "100%",
											id: "fDBvepaDX",
											layoutId: "fDBvepaDX",
											variant: matchVariant("nf35aEDlg"),
											width: "100%",
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider>
							</motion.div>
						)}
					</motion.header>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-B7oPy.framer-zagk1c, .framer-B7oPy .framer-zagk1c { display: block; }",
	".framer-B7oPy.framer-14x3d1s { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 30px 36px 30px 36px; position: relative; width: 1200px; }",
	".framer-B7oPy .framer-fpkjic { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-B7oPy .framer-1iby9z9 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; text-decoration: none; width: min-content; }",
	".framer-B7oPy .framer-89dhfu { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-B7oPy .framer-e4ig5p { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 30px; height: min-content; justify-content: flex-end; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-B7oPy .framer-102v5yv-container, .framer-B7oPy .framer-16qi4b4-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-B7oPy .framer-1hsaif8-container { flex: none; height: 18px; position: relative; width: 18px; }",
	".framer-B7oPy .framer-ddqdi5 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; min-height: calc(var(--framer-viewport-height, 100vh) * 1); overflow: visible; padding: 0px 0px 180px 0px; position: relative; width: 100%; }",
	".framer-B7oPy.framer-v-ode4tf.framer-14x3d1s, .framer-B7oPy.framer-v-1c5dtbo.framer-14x3d1s { padding: 24px 30px 24px 30px; }",
	".framer-B7oPy.framer-v-1lzp3ub.framer-14x3d1s { align-content: flex-start; align-items: flex-start; padding: 20px; width: 360px; }",
	".framer-B7oPy.framer-v-1xhzf5f.framer-14x3d1s { align-content: flex-start; align-items: flex-start; min-height: calc(var(--framer-viewport-height, 100vh) * 1); overflow: auto; overscroll-behavior: none; padding: 20px; width: 360px; }",
	'.framer-B7oPy[data-border="true"]::after, .framer-B7oPy [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
var Framerx8X7x6HpE = withCSS(Component, css, "framer-B7oPy");
var stdin_default3 = Framerx8X7x6HpE;
Framerx8X7x6HpE.displayName = "Navigation";
Framerx8X7x6HpE.defaultProps = {
	height: 93,
	width: 1200,
};
addPropertyControls(Framerx8X7x6HpE, {
	variant: {
		options: [
			"ttIMsCdGf",
			"YxAczhV6j",
			"bNJrsTReY",
			"rqjaZSxtJ",
			"ANBzqZO9P",
			"lOX7ou7Ng",
		],
		optionTitles: [
			"Desktop - Close",
			"Desktop - Open",
			"Tablet - Close",
			"Tablet - Open",
			"Mobile - Close",
			"Mobile - Open",
		],
		title: "Variant",
		type: ControlType.Enum,
	},
	Miu51ahMm: {
		title: "Cursor",
		type: ControlType.CustomCursor,
	},
});
addFonts(
	Framerx8X7x6HpE,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/DpPBYI0sL4fYLgAkX8KXOPVt7c.woff2",
					weight: "700",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/4RAEQdEOrcnDkhHiiCbJOw92Lk.woff2",
					weight: "700",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/1K3W8DizY3v4emK8Mb08YHxTbs.woff2",
					weight: "700",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/tUSCtfYVM1I1IchuyCwz9gDdQ.woff2",
					weight: "700",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/VgYFWiwsAC5OYxAycRXXvhze58.woff2",
					weight: "700",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/syRNPWzAMIrcJ3wIlPIP43KjQs.woff2",
					weight: "700",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/GIryZETIX4IFypco5pYZONKhJIo.woff2",
					weight: "700",
				},
			],
		},
		...MenuFonts,
		...MenuButtonFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:navigation
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "ANBzqZO9P",
	md: "bNJrsTReY",
	xl: "ttIMsCdGf",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"b917fc1195920e6c8a50255315bde13451700c9dc2ee3323349c54f78331e19f"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default3, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders NavigationFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"b917fc1195920e6c8a50255315bde13451700c9dc2ee3323349c54f78331e19f"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default3}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default3);
var navigation_default = ComponentWithRoot;
export { navigation_default as default };
