// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project b917fc1195920e6c "Portfolio", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Default' | 'Service 1' | 'Service 2' | 'Service 3' | 'Service 4' | 'Service 5' | 'Service 6' | 'Service 7' | 'Service 8' | 'Mobile' // Variant
 * service1?: string // Service 1
 * service1?: {src: string, srcSet?: string, alt?: string} // Service 1
 * service2?: string // Service 2
 * service2?: {src: string, srcSet?: string, alt?: string} // Service 2
 * service3?: string // Service 3
 * service3?: {src: string, srcSet?: string, alt?: string} // Service 3
 * service4?: string // Service 4
 * service4?: {src: string, srcSet?: string, alt?: string} // Service 4
 * service5?: string // Service 5
 * service5?: {src: string, srcSet?: string, alt?: string} // Service 5
 * service6?: string // Service 6
 * service6?: {src: string, srcSet?: string, alt?: string} // Service 6
 * service7?: string // Service 7
 * service7?: {src: string, srcSet?: string, alt?: string} // Service 7
 * service8?: string // Service 8
 * service8?: {src: string, srcSet?: string, alt?: string} // Service 8
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-57F2Y2KU.js";
import { routes } from "./chunks/chunk-MBSQQC4T.js";

// virtual:services
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/bzOVN2qa97TmVHxKHtqx/A5dDw8NuPFyEiN2U11Ag/sATi3SnVj.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var RichTextWithFX = withFX(RichText);
var ImageWithFX = withFX(Image);
var cycleOrder = [
	"Z3xXhgUUc",
	"MUCjkXBNK",
	"XARj6KQm_",
	"ONBpqfV0W",
	"FikcgJh5c",
	"rq_7lOxBM",
	"T0FL1U0qV",
	"j2MqAs_Oi",
	"ENqozI4SF",
	"h2GSKcPC8",
];
var serializationHash = "framer-ukF83";
var variantClassNames = {
	ENqozI4SF: "framer-v-1vg4x3",
	FikcgJh5c: "framer-v-1uwiq8j",
	h2GSKcPC8: "framer-v-13les4d",
	j2MqAs_Oi: "framer-v-15ldrns",
	MUCjkXBNK: "framer-v-130s30c",
	ONBpqfV0W: "framer-v-yclkcz",
	rq_7lOxBM: "framer-v-6z6v96",
	T0FL1U0qV: "framer-v-1r33l72",
	XARj6KQm_: "framer-v-bhawua",
	Z3xXhgUUc: "framer-v-1tkygj1",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transition1 = {
	delay: 0,
	duration: 0.5,
	ease: [0.03, 1.09, 0.45, 1.03],
	type: "tween",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var animation = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 100,
};
var transition2 = {
	delay: 0,
	duration: 1.4,
	ease: [0, 0.56, 0.26, 0.97],
	type: "tween",
};
var animation1 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition2,
	x: 0,
	y: 100,
};
var isSet = (value) => {
	if (Array.isArray(value)) return value.length > 0;
	return value !== void 0 && value !== null && value !== "";
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Service 1": "MUCjkXBNK",
	"Service 2": "XARj6KQm_",
	"Service 3": "ONBpqfV0W",
	"Service 4": "FikcgJh5c",
	"Service 5": "rq_7lOxBM",
	"Service 6": "T0FL1U0qV",
	"Service 7": "j2MqAs_Oi",
	"Service 8": "ENqozI4SF",
	Default: "Z3xXhgUUc",
	Mobile: "h2GSKcPC8",
};
var getProps = ({
	height,
	id,
	service1,
	service11,
	service2,
	service21,
	service3,
	service31,
	service4,
	service41,
	service5,
	service51,
	service6,
	service61,
	service7,
	service71,
	service8,
	service81,
	width,
	...props
}) => {
	var _ref,
		_ref1,
		_ref2,
		_ref3,
		_ref4,
		_ref5,
		_ref6,
		_humanReadableVariantMap_props_variant,
		_ref7,
		_ref8;
	return {
		...props,
		Ar6FZbMbq:
			service51 !== null && service51 !== void 0 ? service51 : props.Ar6FZbMbq,
		cIOsuIEkl:
			(_ref =
				service4 !== null && service4 !== void 0
					? service4
					: props.cIOsuIEkl) !== null && _ref !== void 0
				? _ref
				: "Service_04",
		cwup7DuIy:
			(_ref1 =
				service1 !== null && service1 !== void 0
					? service1
					: props.cwup7DuIy) !== null && _ref1 !== void 0
				? _ref1
				: "Service_01",
		glL7dPde1:
			(_ref2 =
				service6 !== null && service6 !== void 0
					? service6
					: props.glL7dPde1) !== null && _ref2 !== void 0
				? _ref2
				: "Service_06",
		JB6Gdzh2Y:
			service81 !== null && service81 !== void 0 ? service81 : props.JB6Gdzh2Y,
		jIeFGDszv:
			(_ref3 =
				service5 !== null && service5 !== void 0
					? service5
					: props.jIeFGDszv) !== null && _ref3 !== void 0
				? _ref3
				: "Service_05",
		KliwFVhHo:
			service11 !== null && service11 !== void 0 ? service11 : props.KliwFVhHo,
		mVaqMa1We:
			(_ref4 =
				service3 !== null && service3 !== void 0
					? service3
					: props.mVaqMa1We) !== null && _ref4 !== void 0
				? _ref4
				: "Service_03",
		mwSFKIAbz:
			(_ref5 =
				service7 !== null && service7 !== void 0
					? service7
					: props.mwSFKIAbz) !== null && _ref5 !== void 0
				? _ref5
				: "Service_07",
		shcoV5hhw:
			(_ref6 =
				service2 !== null && service2 !== void 0
					? service2
					: props.shcoV5hhw) !== null && _ref6 !== void 0
				? _ref6
				: "Service_02",
		UAL4miu_h:
			service61 !== null && service61 !== void 0 ? service61 : props.UAL4miu_h,
		uEJS2il6J:
			service31 !== null && service31 !== void 0 ? service31 : props.uEJS2il6J,
		variant:
			(_ref7 =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref7 !== void 0
				? _ref7
				: "Z3xXhgUUc",
		vGI0mfGZO:
			service71 !== null && service71 !== void 0 ? service71 : props.vGI0mfGZO,
		VHrllqyHR:
			(_ref8 =
				service8 !== null && service8 !== void 0
					? service8
					: props.VHrllqyHR) !== null && _ref8 !== void 0
				? _ref8
				: "Service_08",
		Xbv4bIwCr:
			service41 !== null && service41 !== void 0 ? service41 : props.Xbv4bIwCr,
		zWAknQVxL:
			service21 !== null && service21 !== void 0 ? service21 : props.zWAknQVxL,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		cwup7DuIy,
		KliwFVhHo,
		shcoV5hhw,
		zWAknQVxL,
		mVaqMa1We,
		uEJS2il6J,
		cIOsuIEkl,
		Xbv4bIwCr,
		jIeFGDszv,
		Ar6FZbMbq,
		glL7dPde1,
		UAL4miu_h,
		mwSFKIAbz,
		vGI0mfGZO,
		VHrllqyHR,
		JB6Gdzh2Y,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "Z3xXhgUUc",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onMouseLeavenpw951 = activeVariantCallback(async (...args) => {
		setGestureState({
			isHovered: false,
		});
		setVariant("Z3xXhgUUc");
	});
	const onMouseEnterumkt9d = activeVariantCallback(async (...args) => {
		setVariant("MUCjkXBNK");
	});
	const onMouseLeaveqta605 = activeVariantCallback(async (...args) => {
		setVariant("Z3xXhgUUc");
	});
	const onMouseEnter1o4ay6h = activeVariantCallback(async (...args) => {
		setVariant("XARj6KQm_");
	});
	const onTapqta605 = activeVariantCallback(async (...args) => {
		setVariant("Z3xXhgUUc");
	});
	const onMouseEnter1xssnj3 = activeVariantCallback(async (...args) => {
		setVariant("ONBpqfV0W");
	});
	const onMouseEnter1r7tvwq = activeVariantCallback(async (...args) => {
		setVariant("FikcgJh5c");
	});
	const onMouseEnter16apa32 = activeVariantCallback(async (...args) => {
		setVariant("rq_7lOxBM");
	});
	const onMouseEnterjs0xal = activeVariantCallback(async (...args) => {
		setVariant("T0FL1U0qV");
	});
	const onMouseEnterp9x99 = activeVariantCallback(async (...args) => {
		setVariant("j2MqAs_Oi");
	});
	const onMouseEnter1hsvf20 = activeVariantCallback(async (...args) => {
		setVariant("ENqozI4SF");
	});
	const ref1 = React.useRef(null);
	const visible = isSet(KliwFVhHo);
	const isDisplayed = (value) => {
		if (baseVariant === "h2GSKcPC8") return value;
		return false;
	};
	const visible1 = isSet(zWAknQVxL);
	const visible2 = isSet(uEJS2il6J);
	const visible3 = isSet(Xbv4bIwCr);
	const visible4 = isSet(Ar6FZbMbq);
	const visible5 = isSet(UAL4miu_h);
	const visible6 = isSet(vGI0mfGZO);
	const visible7 = isSet(JB6Gdzh2Y);
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [className];
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							serializationHash,
							...sharedStyleClassNames,
							"framer-1tkygj1",
							className2,
							classNames,
						)}
						data-framer-name={"Default"}
						layoutDependency={layoutDependency}
						layoutId={"Z3xXhgUUc"}
						ref={ref !== null && ref !== void 0 ? ref : ref1}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								ENqozI4SF: {
									"data-framer-name": "Service 8",
								},
								FikcgJh5c: {
									"data-framer-name": "Service 4",
								},
								h2GSKcPC8: {
									"data-framer-name": "Mobile",
								},
								j2MqAs_Oi: {
									"data-framer-name": "Service 7",
								},
								MUCjkXBNK: {
									"data-framer-name": "Service 1",
								},
								ONBpqfV0W: {
									"data-framer-name": "Service 3",
									"data-highlight": true,
									onMouseLeave: onMouseLeavenpw951,
								},
								rq_7lOxBM: {
									"data-framer-name": "Service 5",
								},
								T0FL1U0qV: {
									"data-framer-name": "Service 6",
								},
								XARj6KQm_: {
									"data-framer-name": "Service 2",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<Image
							background={{
								alt: "",
								fit: "fill",
							}}
							className={"framer-1375ib1"}
							data-framer-name={"Image"}
							layoutDependency={layoutDependency}
							layoutId={"JXLvkZFPU"}
							style={{
								opacity: 0,
								rotate: 0,
							}}
							variants={{
								ENqozI4SF: {
									opacity: 1,
									rotate: 5,
								},
								FikcgJh5c: {
									opacity: 1,
									rotate: 5,
								},
								j2MqAs_Oi: {
									opacity: 1,
									rotate: -5,
								},
								MUCjkXBNK: {
									opacity: 1,
									rotate: -5,
								},
								ONBpqfV0W: {
									opacity: 1,
									rotate: -5,
								},
								rq_7lOxBM: {
									opacity: 1,
									rotate: -5,
								},
								T0FL1U0qV: {
									opacity: 1,
									rotate: 5,
								},
								XARj6KQm_: {
									opacity: 1,
									rotate: 5,
								},
							}}
							{...addPropertyOverrides(
								{
									ENqozI4SF: {
										background: {
											alt: "",
											loading: getLoadingLazyAtYPosition(
												((componentViewport === null ||
												componentViewport === void 0
													? void 0
													: componentViewport.y) || 0) + 537,
											),
											sizes: "438px",
											...toResponsiveImage(JB6Gdzh2Y),
											...{
												positionX: "center",
												positionY: "center",
											},
										},
									},
									FikcgJh5c: {
										background: {
											alt: "",
											loading: getLoadingLazyAtYPosition(
												((componentViewport === null ||
												componentViewport === void 0
													? void 0
													: componentViewport.y) || 0) + 109,
											),
											sizes: "438px",
											...toResponsiveImage(Xbv4bIwCr),
											...{
												positionX: "center",
												positionY: "center",
											},
										},
									},
									j2MqAs_Oi: {
										background: {
											alt: "",
											loading: getLoadingLazyAtYPosition(
												((componentViewport === null ||
												componentViewport === void 0
													? void 0
													: componentViewport.y) || 0) + 428,
											),
											sizes: "438px",
											...toResponsiveImage(vGI0mfGZO),
											...{
												positionX: "center",
												positionY: "center",
											},
										},
									},
									MUCjkXBNK: {
										background: {
											alt: "",
											loading: getLoadingLazyAtYPosition(
												((componentViewport === null ||
												componentViewport === void 0
													? void 0
													: componentViewport.y) || 0) + -212.5,
											),
											sizes: "438px",
											...toResponsiveImage(KliwFVhHo),
											...{
												positionX: "center",
												positionY: "center",
											},
										},
									},
									ONBpqfV0W: {
										background: {
											alt: "",
											loading: getLoadingLazyAtYPosition(
												((componentViewport === null ||
												componentViewport === void 0
													? void 0
													: componentViewport.y) || 0) + -0.5,
											),
											sizes: "438px",
											...toResponsiveImage(uEJS2il6J),
											...{
												positionX: "center",
												positionY: "center",
											},
										},
									},
									rq_7lOxBM: {
										background: {
											alt: "",
											loading: getLoadingLazyAtYPosition(
												((componentViewport === null ||
												componentViewport === void 0
													? void 0
													: componentViewport.y) || 0) + 216,
											),
											sizes: "438px",
											...toResponsiveImage(Ar6FZbMbq),
											...{
												positionX: "center",
												positionY: "center",
											},
										},
									},
									T0FL1U0qV: {
										background: {
											alt: "",
											loading: getLoadingLazyAtYPosition(
												((componentViewport === null ||
												componentViewport === void 0
													? void 0
													: componentViewport.y) || 0) + 323,
											),
											sizes: "438px",
											...toResponsiveImage(UAL4miu_h),
											...{
												positionX: "center",
												positionY: "center",
											},
										},
									},
									XARj6KQm_: {
										background: {
											alt: "",
											fit: "fill",
											loading: getLoadingLazyAtYPosition(
												((componentViewport === null ||
												componentViewport === void 0
													? void 0
													: componentViewport.y) || 0) + -105.5,
											),
											sizes: "438px",
											...toResponsiveImage(zWAknQVxL),
										},
									},
								},
								baseVariant,
								gestureVariant,
							)}
						/>
						<motion.div
							className={"framer-4hn12h"}
							data-framer-name={"Service 1"}
							layoutDependency={layoutDependency}
							layoutId={"EQzEnO3zH"}
						>
							<RichTextWithFX
								__framer__animate={{
									transition: transition2,
								}}
								__framer__animateOnce={true}
								__framer__enter={animation}
								__framer__exit={animation1}
								__framer__styleAppearEffectEnabled={true}
								__framer__threshold={0}
								__fromCanvasComponent={true}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								className={"framer-1p6sejj"}
								data-framer-name={"Service 1"}
								data-highlight={true}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"IJyrmBLNl"}
								onMouseEnter={onMouseEnterumkt9d}
								style={{
									"--extracted-a0htzi":
										"var(--token-e9abed44-df8b-4765-bbfe-7c072006d47b, rgb(0, 0, 0))",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
									opacity: 1,
								}}
								text={cwup7DuIy}
								variants={{
									ENqozI4SF: {
										opacity: 0.2,
									},
									FikcgJh5c: {
										opacity: 0.2,
									},
									j2MqAs_Oi: {
										opacity: 0.2,
									},
									ONBpqfV0W: {
										opacity: 0.2,
									},
									rq_7lOxBM: {
										opacity: 0.2,
									},
									T0FL1U0qV: {
										opacity: 0.2,
									},
									XARj6KQm_: {
										opacity: 0.2,
									},
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										ENqozI4SF: {
											__targetOpacity: 0.2,
										},
										FikcgJh5c: {
											__targetOpacity: 0.2,
										},
										h2GSKcPC8: {
											"data-highlight": void 0,
											onMouseEnter: void 0,
										},
										j2MqAs_Oi: {
											__targetOpacity: 0.2,
										},
										MUCjkXBNK: {
											onMouseLeave: onMouseLeaveqta605,
										},
										ONBpqfV0W: {
											__targetOpacity: 0.2,
										},
										rq_7lOxBM: {
											__targetOpacity: 0.2,
										},
										T0FL1U0qV: {
											__targetOpacity: 0.2,
										},
										XARj6KQm_: {
											__targetOpacity: 0.2,
											onMouseLeave: onMouseLeaveqta605,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React.Fragment>
									<motion.h3
										className={"framer-styles-preset-elkczp"}
										data-styles-preset={"EbGvsRf0g"}
										style={{
											"--framer-text-color":
												"var(--extracted-a0htzi, var(--token-e9abed44-df8b-4765-bbfe-7c072006d47b, rgb(0, 0, 0)))",
										}}
									>
										{"Service_01"}
									</motion.h3>
								</React.Fragment>
							</RichTextWithFX>
							{isDisplayed(visible) && (
								<ImageWithFX
									__framer__animate={{
										transition: transition2,
									}}
									__framer__animateOnce={true}
									__framer__enter={animation}
									__framer__exit={animation1}
									__framer__styleAppearEffectEnabled={true}
									__framer__threshold={0}
									__perspectiveFX={false}
									__smartComponentFX={true}
									__targetOpacity={1}
									background={{
										alt: "",
										fit: "fill",
										...toResponsiveImage(KliwFVhHo),
									}}
									className={"framer-1oxl1jq"}
									layoutDependency={layoutDependency}
									layoutId={"aIyLa6Fea"}
									{...addPropertyOverrides(
										{
											h2GSKcPC8: {
												background: {
													alt: "",
													fit: "fill",
													loading: getLoadingLazyAtYPosition(
														((componentViewport === null ||
														componentViewport === void 0
															? void 0
															: componentViewport.y) || 0) +
															0 +
															((((componentViewport === null ||
															componentViewport === void 0
																? void 0
																: componentViewport.height) || 776) -
																0 -
																776) /
																2 +
																0 +
																0) +
															20.5,
													),
													sizes: "49px",
													...toResponsiveImage(KliwFVhHo),
												},
											},
										},
										baseVariant,
										gestureVariant,
									)}
								/>
							)}
						</motion.div>
						<motion.div
							className={"framer-sqtetk"}
							data-framer-name={"Service 2"}
							layoutDependency={layoutDependency}
							layoutId={"mG2tzPIl3"}
						>
							<RichTextWithFX
								__framer__animate={{
									transition: transition2,
								}}
								__framer__animateOnce={true}
								__framer__enter={animation}
								__framer__exit={animation1}
								__framer__styleAppearEffectEnabled={true}
								__framer__threshold={0}
								__fromCanvasComponent={true}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								className={"framer-1iy1q4v"}
								data-framer-name={"Service 2"}
								data-highlight={true}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"qMJYuGqdZ"}
								onMouseEnter={onMouseEnter1o4ay6h}
								style={{
									"--extracted-a0htzi":
										"var(--token-e9abed44-df8b-4765-bbfe-7c072006d47b, rgb(0, 0, 0))",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
									opacity: 1,
								}}
								text={shcoV5hhw}
								variants={{
									ENqozI4SF: {
										opacity: 0.2,
									},
									FikcgJh5c: {
										opacity: 0.2,
									},
									j2MqAs_Oi: {
										opacity: 0.2,
									},
									MUCjkXBNK: {
										opacity: 0.2,
									},
									ONBpqfV0W: {
										opacity: 0.2,
									},
									rq_7lOxBM: {
										opacity: 0.2,
									},
									T0FL1U0qV: {
										opacity: 0.2,
									},
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										ENqozI4SF: {
											__targetOpacity: 0.2,
										},
										FikcgJh5c: {
											__targetOpacity: 0.2,
										},
										h2GSKcPC8: {
											"data-highlight": void 0,
											onMouseEnter: void 0,
										},
										j2MqAs_Oi: {
											__targetOpacity: 0.2,
										},
										MUCjkXBNK: {
											__targetOpacity: 0.2,
											onMouseLeave: onMouseLeaveqta605,
										},
										ONBpqfV0W: {
											__targetOpacity: 0.2,
										},
										rq_7lOxBM: {
											__targetOpacity: 0.2,
										},
										T0FL1U0qV: {
											__targetOpacity: 0.2,
										},
										XARj6KQm_: {
											onMouseLeave: onMouseLeaveqta605,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React.Fragment>
									<motion.h3
										className={"framer-styles-preset-elkczp"}
										data-styles-preset={"EbGvsRf0g"}
										style={{
											"--framer-text-color":
												"var(--extracted-a0htzi, var(--token-e9abed44-df8b-4765-bbfe-7c072006d47b, rgb(0, 0, 0)))",
										}}
									>
										{"Service_02"}
									</motion.h3>
								</React.Fragment>
							</RichTextWithFX>
							{isDisplayed(visible1) && (
								<ImageWithFX
									__framer__animate={{
										transition: transition2,
									}}
									__framer__animateOnce={true}
									__framer__enter={animation}
									__framer__exit={animation1}
									__framer__styleAppearEffectEnabled={true}
									__framer__threshold={0}
									__perspectiveFX={false}
									__smartComponentFX={true}
									__targetOpacity={1}
									background={{
										alt: "",
										fit: "fill",
										...toResponsiveImage(zWAknQVxL),
									}}
									className={"framer-1ehomjt"}
									layoutDependency={layoutDependency}
									layoutId={"nZJZOJkM8"}
									{...addPropertyOverrides(
										{
											h2GSKcPC8: {
												background: {
													alt: "",
													fit: "fill",
													loading: getLoadingLazyAtYPosition(
														((componentViewport === null ||
														componentViewport === void 0
															? void 0
															: componentViewport.y) || 0) +
															0 +
															((((componentViewport === null ||
															componentViewport === void 0
																? void 0
																: componentViewport.height) || 776) -
																0 -
																776) /
																2 +
																90 +
																8) +
															21,
													),
													sizes: "48px",
													...toResponsiveImage(zWAknQVxL),
												},
											},
										},
										baseVariant,
										gestureVariant,
									)}
								/>
							)}
						</motion.div>
						<motion.div
							className={"framer-14bk1zl"}
							data-framer-name={"Service 3"}
							layoutDependency={layoutDependency}
							layoutId={"zTkYzR226"}
						>
							<RichTextWithFX
								__framer__animate={{
									transition: transition2,
								}}
								__framer__animateOnce={true}
								__framer__enter={animation}
								__framer__exit={animation1}
								__framer__styleAppearEffectEnabled={true}
								__framer__threshold={0}
								__fromCanvasComponent={true}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								className={"framer-sy3sle"}
								data-framer-name={"Service 3"}
								data-highlight={true}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"Re7sgYVCI"}
								onMouseEnter={onMouseEnter1xssnj3}
								onTap={onTapqta605}
								style={{
									"--extracted-a0htzi":
										"var(--token-e9abed44-df8b-4765-bbfe-7c072006d47b, rgb(0, 0, 0))",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
									opacity: 1,
								}}
								text={mVaqMa1We}
								variants={{
									ENqozI4SF: {
										opacity: 0.2,
									},
									FikcgJh5c: {
										opacity: 0.2,
									},
									j2MqAs_Oi: {
										opacity: 0.2,
									},
									MUCjkXBNK: {
										opacity: 0.2,
									},
									rq_7lOxBM: {
										opacity: 0.2,
									},
									T0FL1U0qV: {
										opacity: 0.2,
									},
									XARj6KQm_: {
										opacity: 0.2,
									},
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										ENqozI4SF: {
											__targetOpacity: 0.2,
										},
										FikcgJh5c: {
											__targetOpacity: 0.2,
										},
										h2GSKcPC8: {
											onMouseEnter: void 0,
										},
										j2MqAs_Oi: {
											__targetOpacity: 0.2,
										},
										MUCjkXBNK: {
											__targetOpacity: 0.2,
										},
										ONBpqfV0W: {
											onMouseLeave: onMouseLeaveqta605,
										},
										rq_7lOxBM: {
											__targetOpacity: 0.2,
										},
										T0FL1U0qV: {
											__targetOpacity: 0.2,
										},
										XARj6KQm_: {
											__targetOpacity: 0.2,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React.Fragment>
									<motion.h3
										className={"framer-styles-preset-elkczp"}
										data-styles-preset={"EbGvsRf0g"}
										style={{
											"--framer-text-color":
												"var(--extracted-a0htzi, var(--token-e9abed44-df8b-4765-bbfe-7c072006d47b, rgb(0, 0, 0)))",
										}}
									>
										{"Service_03"}
									</motion.h3>
								</React.Fragment>
							</RichTextWithFX>
							{isDisplayed(visible2) && (
								<ImageWithFX
									__framer__animate={{
										transition: transition2,
									}}
									__framer__animateOnce={true}
									__framer__enter={animation}
									__framer__exit={animation1}
									__framer__styleAppearEffectEnabled={true}
									__framer__threshold={0}
									__perspectiveFX={false}
									__smartComponentFX={true}
									__targetOpacity={1}
									background={{
										alt: "",
										fit: "fill",
										...toResponsiveImage(uEJS2il6J),
										...{
											positionX: "center",
											positionY: "center",
										},
									}}
									className={"framer-1v7ovni"}
									layoutDependency={layoutDependency}
									layoutId={"JLcje00PU"}
									{...addPropertyOverrides(
										{
											h2GSKcPC8: {
												background: {
													alt: "",
													fit: "fill",
													loading: getLoadingLazyAtYPosition(
														((componentViewport === null ||
														componentViewport === void 0
															? void 0
															: componentViewport.y) || 0) +
															0 +
															((((componentViewport === null ||
															componentViewport === void 0
																? void 0
																: componentViewport.height) || 776) -
																0 -
																776) /
																2 +
																180 +
																16) +
															21,
													),
													sizes: "48px",
													...toResponsiveImage(uEJS2il6J),
													...{
														positionX: "center",
														positionY: "center",
													},
												},
											},
										},
										baseVariant,
										gestureVariant,
									)}
								/>
							)}
						</motion.div>
						<motion.div
							className={"framer-1fc1b7r"}
							data-framer-name={"Service 4"}
							layoutDependency={layoutDependency}
							layoutId={"hNsmVYNgg"}
						>
							<RichTextWithFX
								__framer__animate={{
									transition: transition2,
								}}
								__framer__animateOnce={true}
								__framer__enter={animation}
								__framer__exit={animation1}
								__framer__styleAppearEffectEnabled={true}
								__framer__threshold={0}
								__fromCanvasComponent={true}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								className={"framer-1czcz5c"}
								data-framer-name={"Service 4"}
								data-highlight={true}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"SHLxDKNIT"}
								onMouseEnter={onMouseEnter1r7tvwq}
								style={{
									"--extracted-a0htzi":
										"var(--token-e9abed44-df8b-4765-bbfe-7c072006d47b, rgb(0, 0, 0))",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
									opacity: 1,
								}}
								text={cIOsuIEkl}
								variants={{
									ENqozI4SF: {
										opacity: 0.2,
									},
									j2MqAs_Oi: {
										opacity: 0.2,
									},
									MUCjkXBNK: {
										opacity: 0.2,
									},
									ONBpqfV0W: {
										opacity: 0.2,
									},
									rq_7lOxBM: {
										opacity: 0.2,
									},
									T0FL1U0qV: {
										opacity: 0.2,
									},
									XARj6KQm_: {
										opacity: 0.2,
									},
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										ENqozI4SF: {
											__targetOpacity: 0.2,
										},
										FikcgJh5c: {
											onMouseLeave: onMouseLeaveqta605,
										},
										h2GSKcPC8: {
											"data-highlight": void 0,
											onMouseEnter: void 0,
										},
										j2MqAs_Oi: {
											__targetOpacity: 0.2,
										},
										MUCjkXBNK: {
											__targetOpacity: 0.2,
										},
										ONBpqfV0W: {
											__targetOpacity: 0.2,
										},
										rq_7lOxBM: {
											__targetOpacity: 0.2,
										},
										T0FL1U0qV: {
											__targetOpacity: 0.2,
										},
										XARj6KQm_: {
											__targetOpacity: 0.2,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React.Fragment>
									<motion.h3
										className={"framer-styles-preset-elkczp"}
										data-styles-preset={"EbGvsRf0g"}
										style={{
											"--framer-text-color":
												"var(--extracted-a0htzi, var(--token-e9abed44-df8b-4765-bbfe-7c072006d47b, rgb(0, 0, 0)))",
										}}
									>
										{"Service_04"}
									</motion.h3>
								</React.Fragment>
							</RichTextWithFX>
							{isDisplayed(visible3) && (
								<ImageWithFX
									__framer__animate={{
										transition: transition2,
									}}
									__framer__animateOnce={true}
									__framer__enter={animation}
									__framer__exit={animation1}
									__framer__styleAppearEffectEnabled={true}
									__framer__threshold={0}
									__perspectiveFX={false}
									__smartComponentFX={true}
									__targetOpacity={1}
									background={{
										alt: "",
										fit: "fill",
										...toResponsiveImage(Xbv4bIwCr),
										...{
											positionX: "center",
											positionY: "center",
										},
									}}
									className={"framer-1vtzu72"}
									layoutDependency={layoutDependency}
									layoutId={"W_b7CxI44"}
									{...addPropertyOverrides(
										{
											h2GSKcPC8: {
												background: {
													alt: "",
													fit: "fill",
													loading: getLoadingLazyAtYPosition(
														((componentViewport === null ||
														componentViewport === void 0
															? void 0
															: componentViewport.y) || 0) +
															0 +
															((((componentViewport === null ||
															componentViewport === void 0
																? void 0
																: componentViewport.height) || 776) -
																0 -
																776) /
																2 +
																270 +
																24) +
															21,
													),
													sizes: "48px",
													...toResponsiveImage(Xbv4bIwCr),
													...{
														positionX: "center",
														positionY: "center",
													},
												},
											},
										},
										baseVariant,
										gestureVariant,
									)}
								/>
							)}
						</motion.div>
						<motion.div
							className={"framer-7ctwu9"}
							data-framer-name={"Service 5"}
							layoutDependency={layoutDependency}
							layoutId={"bnEvyvfYI"}
						>
							<RichTextWithFX
								__framer__animate={{
									transition: transition2,
								}}
								__framer__animateOnce={true}
								__framer__enter={animation}
								__framer__exit={animation1}
								__framer__styleAppearEffectEnabled={true}
								__framer__threshold={0}
								__fromCanvasComponent={true}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								className={"framer-1nmvj1g"}
								data-framer-name={"Service 5"}
								data-highlight={true}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"ChIGYcSr6"}
								onMouseEnter={onMouseEnter16apa32}
								style={{
									"--extracted-a0htzi":
										"var(--token-e9abed44-df8b-4765-bbfe-7c072006d47b, rgb(0, 0, 0))",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
									opacity: 1,
								}}
								text={jIeFGDszv}
								variants={{
									ENqozI4SF: {
										opacity: 0.2,
									},
									FikcgJh5c: {
										opacity: 0.2,
									},
									j2MqAs_Oi: {
										opacity: 0.2,
									},
									MUCjkXBNK: {
										opacity: 0.2,
									},
									ONBpqfV0W: {
										opacity: 0.2,
									},
									T0FL1U0qV: {
										opacity: 0.2,
									},
									XARj6KQm_: {
										opacity: 0.2,
									},
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										ENqozI4SF: {
											__targetOpacity: 0.2,
										},
										FikcgJh5c: {
											__targetOpacity: 0.2,
										},
										h2GSKcPC8: {
											"data-highlight": void 0,
											onMouseEnter: void 0,
										},
										j2MqAs_Oi: {
											__targetOpacity: 0.2,
										},
										MUCjkXBNK: {
											__targetOpacity: 0.2,
										},
										ONBpqfV0W: {
											__targetOpacity: 0.2,
										},
										rq_7lOxBM: {
											onMouseLeave: onMouseLeaveqta605,
										},
										T0FL1U0qV: {
											__targetOpacity: 0.2,
										},
										XARj6KQm_: {
											__targetOpacity: 0.2,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React.Fragment>
									<motion.h3
										className={"framer-styles-preset-elkczp"}
										data-styles-preset={"EbGvsRf0g"}
										style={{
											"--framer-text-color":
												"var(--extracted-a0htzi, var(--token-e9abed44-df8b-4765-bbfe-7c072006d47b, rgb(0, 0, 0)))",
										}}
									>
										{"Service_05"}
									</motion.h3>
								</React.Fragment>
							</RichTextWithFX>
							{isDisplayed(visible4) && (
								<ImageWithFX
									__framer__animate={{
										transition: transition2,
									}}
									__framer__animateOnce={true}
									__framer__enter={animation}
									__framer__exit={animation1}
									__framer__styleAppearEffectEnabled={true}
									__framer__threshold={0}
									__perspectiveFX={false}
									__smartComponentFX={true}
									__targetOpacity={1}
									background={{
										alt: "",
										fit: "fill",
										...toResponsiveImage(Ar6FZbMbq),
										...{
											positionX: "center",
											positionY: "center",
										},
									}}
									className={"framer-1s2jj8h"}
									layoutDependency={layoutDependency}
									layoutId={"E1rFw4gS_"}
									{...addPropertyOverrides(
										{
											h2GSKcPC8: {
												background: {
													alt: "",
													fit: "fill",
													loading: getLoadingLazyAtYPosition(
														((componentViewport === null ||
														componentViewport === void 0
															? void 0
															: componentViewport.y) || 0) +
															0 +
															((((componentViewport === null ||
															componentViewport === void 0
																? void 0
																: componentViewport.height) || 776) -
																0 -
																776) /
																2 +
																360 +
																32) +
															21,
													),
													sizes: "48px",
													...toResponsiveImage(Ar6FZbMbq),
													...{
														positionX: "center",
														positionY: "center",
													},
												},
											},
										},
										baseVariant,
										gestureVariant,
									)}
								/>
							)}
						</motion.div>
						<motion.div
							className={"framer-59alh"}
							data-framer-name={"Service 6"}
							layoutDependency={layoutDependency}
							layoutId={"dAhydJOnc"}
						>
							<RichTextWithFX
								__framer__animate={{
									transition: transition2,
								}}
								__framer__animateOnce={true}
								__framer__enter={animation}
								__framer__exit={animation1}
								__framer__styleAppearEffectEnabled={true}
								__framer__threshold={0}
								__fromCanvasComponent={true}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								className={"framer-2lpewp"}
								data-framer-name={"Service 6"}
								data-highlight={true}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"sVoE4aUVl"}
								onMouseEnter={onMouseEnterjs0xal}
								style={{
									"--extracted-a0htzi":
										"var(--token-e9abed44-df8b-4765-bbfe-7c072006d47b, rgb(0, 0, 0))",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
									opacity: 1,
								}}
								text={glL7dPde1}
								variants={{
									ENqozI4SF: {
										opacity: 0.2,
									},
									FikcgJh5c: {
										opacity: 0.2,
									},
									j2MqAs_Oi: {
										opacity: 0.2,
									},
									MUCjkXBNK: {
										opacity: 0.2,
									},
									ONBpqfV0W: {
										opacity: 0.2,
									},
									rq_7lOxBM: {
										opacity: 0.2,
									},
									XARj6KQm_: {
										opacity: 0.2,
									},
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										ENqozI4SF: {
											__targetOpacity: 0.2,
										},
										FikcgJh5c: {
											__targetOpacity: 0.2,
										},
										h2GSKcPC8: {
											"data-highlight": void 0,
											onMouseEnter: void 0,
										},
										j2MqAs_Oi: {
											__targetOpacity: 0.2,
										},
										MUCjkXBNK: {
											__targetOpacity: 0.2,
										},
										ONBpqfV0W: {
											__targetOpacity: 0.2,
										},
										rq_7lOxBM: {
											__targetOpacity: 0.2,
											onMouseLeave: onMouseLeaveqta605,
										},
										T0FL1U0qV: {
											onMouseLeave: onMouseLeaveqta605,
										},
										XARj6KQm_: {
											__targetOpacity: 0.2,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React.Fragment>
									<motion.h3
										className={"framer-styles-preset-elkczp"}
										data-styles-preset={"EbGvsRf0g"}
										style={{
											"--framer-text-color":
												"var(--extracted-a0htzi, var(--token-e9abed44-df8b-4765-bbfe-7c072006d47b, rgb(0, 0, 0)))",
										}}
									>
										{"Service_06"}
									</motion.h3>
								</React.Fragment>
							</RichTextWithFX>
							{isDisplayed(visible5) && (
								<Image
									background={{
										alt: "",
										fit: "fill",
										...toResponsiveImage(UAL4miu_h),
										...{
											positionX: "center",
											positionY: "center",
										},
									}}
									className={"framer-lgorb9"}
									layoutDependency={layoutDependency}
									layoutId={"WsMXP0Sl9"}
									{...addPropertyOverrides(
										{
											h2GSKcPC8: {
												background: {
													alt: "",
													fit: "fill",
													loading: getLoadingLazyAtYPosition(
														((componentViewport === null ||
														componentViewport === void 0
															? void 0
															: componentViewport.y) || 0) +
															0 +
															((((componentViewport === null ||
															componentViewport === void 0
																? void 0
																: componentViewport.height) || 776) -
																0 -
																776) /
																2 +
																450 +
																40) +
															21,
													),
													sizes: "48px",
													...toResponsiveImage(UAL4miu_h),
													...{
														positionX: "center",
														positionY: "center",
													},
												},
											},
										},
										baseVariant,
										gestureVariant,
									)}
								/>
							)}
						</motion.div>
						<motion.div
							className={"framer-wvugo9"}
							data-framer-name={"Service 7"}
							layoutDependency={layoutDependency}
							layoutId={"aB_JNwRxZ"}
						>
							<RichTextWithFX
								__framer__animate={{
									transition: transition2,
								}}
								__framer__animateOnce={true}
								__framer__enter={animation}
								__framer__exit={animation1}
								__framer__styleAppearEffectEnabled={true}
								__framer__threshold={0}
								__fromCanvasComponent={true}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								className={"framer-15jyg9r"}
								data-framer-name={"Service 7"}
								data-highlight={true}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"QHuQI2nwp"}
								onMouseEnter={onMouseEnterp9x99}
								style={{
									"--extracted-a0htzi":
										"var(--token-e9abed44-df8b-4765-bbfe-7c072006d47b, rgb(0, 0, 0))",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
									opacity: 1,
								}}
								text={mwSFKIAbz}
								variants={{
									ENqozI4SF: {
										opacity: 0.2,
									},
									FikcgJh5c: {
										opacity: 0.2,
									},
									MUCjkXBNK: {
										opacity: 0.2,
									},
									ONBpqfV0W: {
										opacity: 0.2,
									},
									rq_7lOxBM: {
										opacity: 0.2,
									},
									T0FL1U0qV: {
										opacity: 0.2,
									},
									XARj6KQm_: {
										opacity: 0.2,
									},
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										ENqozI4SF: {
											__targetOpacity: 0.2,
										},
										FikcgJh5c: {
											__targetOpacity: 0.2,
										},
										h2GSKcPC8: {
											"data-highlight": void 0,
											onMouseEnter: void 0,
										},
										j2MqAs_Oi: {
											onMouseLeave: onMouseLeaveqta605,
										},
										MUCjkXBNK: {
											__targetOpacity: 0.2,
										},
										ONBpqfV0W: {
											__targetOpacity: 0.2,
										},
										rq_7lOxBM: {
											__targetOpacity: 0.2,
											onMouseLeave: onMouseLeaveqta605,
										},
										T0FL1U0qV: {
											__targetOpacity: 0.2,
										},
										XARj6KQm_: {
											__targetOpacity: 0.2,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React.Fragment>
									<motion.h3
										className={"framer-styles-preset-elkczp"}
										data-styles-preset={"EbGvsRf0g"}
										style={{
											"--framer-text-color":
												"var(--extracted-a0htzi, var(--token-e9abed44-df8b-4765-bbfe-7c072006d47b, rgb(0, 0, 0)))",
										}}
									>
										{"Service_07"}
									</motion.h3>
								</React.Fragment>
							</RichTextWithFX>
							{isDisplayed(visible6) && (
								<Image
									background={{
										alt: "",
										fit: "fill",
										...toResponsiveImage(vGI0mfGZO),
										...{
											positionX: "center",
											positionY: "center",
										},
									}}
									className={"framer-zgblg6"}
									layoutDependency={layoutDependency}
									layoutId={"QjxDPVU0T"}
									{...addPropertyOverrides(
										{
											h2GSKcPC8: {
												background: {
													alt: "",
													fit: "fill",
													loading: getLoadingLazyAtYPosition(
														((componentViewport === null ||
														componentViewport === void 0
															? void 0
															: componentViewport.y) || 0) +
															0 +
															((((componentViewport === null ||
															componentViewport === void 0
																? void 0
																: componentViewport.height) || 776) -
																0 -
																776) /
																2 +
																540 +
																48) +
															21,
													),
													sizes: "48px",
													...toResponsiveImage(vGI0mfGZO),
													...{
														positionX: "center",
														positionY: "center",
													},
												},
											},
										},
										baseVariant,
										gestureVariant,
									)}
								/>
							)}
						</motion.div>
						<motion.div
							className={"framer-1mc6ifp"}
							data-framer-name={"Service 8"}
							layoutDependency={layoutDependency}
							layoutId={"DzvfJNV8C"}
						>
							<RichTextWithFX
								__framer__animate={{
									transition: transition2,
								}}
								__framer__animateOnce={true}
								__framer__enter={animation}
								__framer__exit={animation1}
								__framer__styleAppearEffectEnabled={true}
								__framer__threshold={0}
								__fromCanvasComponent={true}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								className={"framer-ogsvz8"}
								data-framer-name={"Service 8"}
								data-highlight={true}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"bCS_KPfkf"}
								onMouseEnter={onMouseEnter1hsvf20}
								style={{
									"--extracted-a0htzi":
										"var(--token-e9abed44-df8b-4765-bbfe-7c072006d47b, rgb(0, 0, 0))",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
									opacity: 1,
								}}
								text={VHrllqyHR}
								variants={{
									FikcgJh5c: {
										opacity: 0.2,
									},
									j2MqAs_Oi: {
										opacity: 0.2,
									},
									MUCjkXBNK: {
										opacity: 0.2,
									},
									ONBpqfV0W: {
										opacity: 0.2,
									},
									rq_7lOxBM: {
										opacity: 0.2,
									},
									T0FL1U0qV: {
										opacity: 0.2,
									},
									XARj6KQm_: {
										opacity: 0.2,
									},
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										ENqozI4SF: {
											onMouseLeave: onMouseLeaveqta605,
										},
										FikcgJh5c: {
											__targetOpacity: 0.2,
										},
										h2GSKcPC8: {
											"data-highlight": void 0,
											onMouseEnter: void 0,
										},
										j2MqAs_Oi: {
											__targetOpacity: 0.2,
										},
										MUCjkXBNK: {
											__targetOpacity: 0.2,
										},
										ONBpqfV0W: {
											__targetOpacity: 0.2,
										},
										rq_7lOxBM: {
											__targetOpacity: 0.2,
											onMouseLeave: onMouseLeaveqta605,
										},
										T0FL1U0qV: {
											__targetOpacity: 0.2,
										},
										XARj6KQm_: {
											__targetOpacity: 0.2,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React.Fragment>
									<motion.h3
										className={"framer-styles-preset-elkczp"}
										data-styles-preset={"EbGvsRf0g"}
										style={{
											"--framer-text-color":
												"var(--extracted-a0htzi, var(--token-e9abed44-df8b-4765-bbfe-7c072006d47b, rgb(0, 0, 0)))",
										}}
									>
										{"Service_08"}
									</motion.h3>
								</React.Fragment>
							</RichTextWithFX>
							{isDisplayed(visible7) && (
								<Image
									background={{
										alt: "",
										fit: "fill",
										...toResponsiveImage(JB6Gdzh2Y),
										...{
											positionX: "center",
											positionY: "center",
										},
									}}
									className={"framer-1balhoc"}
									layoutDependency={layoutDependency}
									layoutId={"U8SclaeZf"}
									{...addPropertyOverrides(
										{
											h2GSKcPC8: {
												background: {
													alt: "",
													fit: "fill",
													loading: getLoadingLazyAtYPosition(
														((componentViewport === null ||
														componentViewport === void 0
															? void 0
															: componentViewport.y) || 0) +
															0 +
															((((componentViewport === null ||
															componentViewport === void 0
																? void 0
																: componentViewport.height) || 776) -
																0 -
																776) /
																2 +
																630 +
																56) +
															21,
													),
													sizes: "48px",
													...toResponsiveImage(JB6Gdzh2Y),
													...{
														positionX: "center",
														positionY: "center",
													},
												},
											},
										},
										baseVariant,
										gestureVariant,
									)}
								/>
							)}
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-ukF83.framer-1q2vl4e, .framer-ukF83 .framer-1q2vl4e { display: block; }",
	".framer-ukF83.framer-1tkygj1 { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1040px; }",
	".framer-ukF83 .framer-1375ib1 { flex: none; height: 525px; left: calc(50.00000000000002% - 438px / 2); overflow: visible; pointer-events: none; position: absolute; top: calc(49.71537001897535% - 525px / 2); width: 438px; z-index: 1; }",
	".framer-ukF83 .framer-4hn12h, .framer-ukF83 .framer-sqtetk, .framer-ukF83 .framer-14bk1zl, .framer-ukF83 .framer-1fc1b7r, .framer-ukF83 .framer-7ctwu9, .framer-ukF83 .framer-59alh, .framer-ukF83 .framer-wvugo9, .framer-ukF83 .framer-1mc6ifp { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-ukF83 .framer-1p6sejj, .framer-ukF83 .framer-1iy1q4v, .framer-ukF83 .framer-1czcz5c, .framer-ukF83 .framer-1nmvj1g, .framer-ukF83 .framer-2lpewp, .framer-ukF83 .framer-15jyg9r, .framer-ukF83 .framer-ogsvz8 { flex: none; height: auto; position: relative; white-space: pre; width: auto; z-index: 0; }",
	".framer-ukF83 .framer-1oxl1jq, .framer-ukF83 .framer-1ehomjt, .framer-ukF83 .framer-1v7ovni, .framer-ukF83 .framer-1vtzu72, .framer-ukF83 .framer-1s2jj8h, .framer-ukF83 .framer-lgorb9, .framer-ukF83 .framer-zgblg6, .framer-ukF83 .framer-1balhoc { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 48px); overflow: visible; pointer-events: none; position: relative; width: 48px; z-index: 1; }",
	".framer-ukF83 .framer-sy3sle { cursor: pointer; flex: none; height: auto; position: relative; white-space: pre; width: auto; z-index: 0; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-ukF83.framer-1tkygj1, .framer-ukF83 .framer-4hn12h, .framer-ukF83 .framer-sqtetk, .framer-ukF83 .framer-14bk1zl, .framer-ukF83 .framer-1fc1b7r, .framer-ukF83 .framer-7ctwu9, .framer-ukF83 .framer-59alh, .framer-ukF83 .framer-wvugo9, .framer-ukF83 .framer-1mc6ifp { gap: 0px; } .framer-ukF83.framer-1tkygj1 > * { margin: 0px; margin-bottom: calc(8px / 2); margin-top: calc(8px / 2); } .framer-ukF83.framer-1tkygj1 > :first-child { margin-top: 0px; } .framer-ukF83.framer-1tkygj1 > :last-child { margin-bottom: 0px; } .framer-ukF83 .framer-4hn12h > *, .framer-ukF83 .framer-sqtetk > *, .framer-ukF83 .framer-14bk1zl > *, .framer-ukF83 .framer-1fc1b7r > *, .framer-ukF83 .framer-7ctwu9 > *, .framer-ukF83 .framer-59alh > *, .framer-ukF83 .framer-wvugo9 > *, .framer-ukF83 .framer-1mc6ifp > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-ukF83 .framer-4hn12h > :first-child, .framer-ukF83 .framer-sqtetk > :first-child, .framer-ukF83 .framer-14bk1zl > :first-child, .framer-ukF83 .framer-1fc1b7r > :first-child, .framer-ukF83 .framer-7ctwu9 > :first-child, .framer-ukF83 .framer-59alh > :first-child, .framer-ukF83 .framer-wvugo9 > :first-child, .framer-ukF83 .framer-1mc6ifp > :first-child { margin-left: 0px; } .framer-ukF83 .framer-4hn12h > :last-child, .framer-ukF83 .framer-sqtetk > :last-child, .framer-ukF83 .framer-14bk1zl > :last-child, .framer-ukF83 .framer-1fc1b7r > :last-child, .framer-ukF83 .framer-7ctwu9 > :last-child, .framer-ukF83 .framer-59alh > :last-child, .framer-ukF83 .framer-wvugo9 > :last-child, .framer-ukF83 .framer-1mc6ifp > :last-child { margin-right: 0px; } }",
	".framer-ukF83.framer-v-130s30c .framer-1375ib1 { order: 0; top: -212px; }",
	".framer-ukF83.framer-v-130s30c .framer-4hn12h, .framer-ukF83.framer-v-13les4d .framer-1p6sejj, .framer-ukF83.framer-v-13les4d .framer-1iy1q4v, .framer-ukF83.framer-v-13les4d .framer-sy3sle, .framer-ukF83.framer-v-13les4d .framer-1czcz5c, .framer-ukF83.framer-v-13les4d .framer-1nmvj1g, .framer-ukF83.framer-v-13les4d .framer-2lpewp, .framer-ukF83.framer-v-13les4d .framer-15jyg9r, .framer-ukF83.framer-v-13les4d .framer-ogsvz8 { order: 1; }",
	".framer-ukF83.framer-v-130s30c .framer-1p6sejj, .framer-ukF83.framer-v-bhawua .framer-1iy1q4v, .framer-ukF83.framer-v-yclkcz .framer-sy3sle, .framer-ukF83.framer-v-1uwiq8j .framer-1czcz5c, .framer-ukF83.framer-v-6z6v96 .framer-1nmvj1g, .framer-ukF83.framer-v-6z6v96 .framer-ogsvz8, .framer-ukF83.framer-v-1r33l72 .framer-2lpewp, .framer-ukF83.framer-v-15ldrns .framer-15jyg9r, .framer-ukF83.framer-v-1vg4x3 .framer-ogsvz8 { z-index: 1; }",
	".framer-ukF83.framer-v-130s30c .framer-sqtetk { order: 2; }",
	".framer-ukF83.framer-v-130s30c .framer-14bk1zl { order: 3; }",
	".framer-ukF83.framer-v-130s30c .framer-1fc1b7r { order: 4; }",
	".framer-ukF83.framer-v-130s30c .framer-7ctwu9 { order: 5; }",
	".framer-ukF83.framer-v-130s30c .framer-59alh { order: 6; }",
	".framer-ukF83.framer-v-130s30c .framer-wvugo9 { order: 7; }",
	".framer-ukF83.framer-v-130s30c .framer-1mc6ifp { order: 8; }",
	".framer-ukF83.framer-v-bhawua .framer-1375ib1 { top: -105px; }",
	".framer-ukF83.framer-v-yclkcz .framer-1375ib1 { top: 0px; }",
	".framer-ukF83.framer-v-1uwiq8j .framer-1375ib1 { top: 109px; }",
	".framer-ukF83.framer-v-6z6v96 .framer-1375ib1 { top: 216px; }",
	".framer-ukF83.framer-v-1r33l72 .framer-1375ib1 { top: 323px; }",
	".framer-ukF83.framer-v-15ldrns .framer-1375ib1 { top: 428px; }",
	".framer-ukF83.framer-v-1vg4x3 .framer-1375ib1 { top: 537px; }",
	".framer-ukF83.framer-v-13les4d.framer-1tkygj1 { align-content: flex-start; align-items: flex-start; }",
	".framer-ukF83.framer-v-13les4d .framer-4hn12h, .framer-ukF83.framer-v-13les4d .framer-sqtetk, .framer-ukF83.framer-v-13les4d .framer-14bk1zl, .framer-ukF83.framer-v-13les4d .framer-1fc1b7r, .framer-ukF83.framer-v-13les4d .framer-7ctwu9, .framer-ukF83.framer-v-13les4d .framer-59alh, .framer-ukF83.framer-v-13les4d .framer-1mc6ifp { gap: 16px; }",
	".framer-ukF83.framer-v-13les4d .framer-1oxl1jq { height: var(--framer-aspect-ratio-supported, 49px); order: 0; width: 49px; }",
	".framer-ukF83.framer-v-13les4d .framer-1ehomjt, .framer-ukF83.framer-v-13les4d .framer-1v7ovni, .framer-ukF83.framer-v-13les4d .framer-1vtzu72, .framer-ukF83.framer-v-13les4d .framer-1s2jj8h, .framer-ukF83.framer-v-13les4d .framer-lgorb9, .framer-ukF83.framer-v-13les4d .framer-zgblg6, .framer-ukF83.framer-v-13les4d .framer-1balhoc { order: 0; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-ukF83.framer-v-13les4d .framer-4hn12h, .framer-ukF83.framer-v-13les4d .framer-sqtetk, .framer-ukF83.framer-v-13les4d .framer-14bk1zl, .framer-ukF83.framer-v-13les4d .framer-1fc1b7r, .framer-ukF83.framer-v-13les4d .framer-7ctwu9, .framer-ukF83.framer-v-13les4d .framer-59alh, .framer-ukF83.framer-v-13les4d .framer-1mc6ifp { gap: 0px; } .framer-ukF83.framer-v-13les4d .framer-4hn12h > *, .framer-ukF83.framer-v-13les4d .framer-sqtetk > *, .framer-ukF83.framer-v-13les4d .framer-14bk1zl > *, .framer-ukF83.framer-v-13les4d .framer-1fc1b7r > *, .framer-ukF83.framer-v-13les4d .framer-7ctwu9 > *, .framer-ukF83.framer-v-13les4d .framer-59alh > *, .framer-ukF83.framer-v-13les4d .framer-1mc6ifp > * { margin: 0px; margin-left: calc(16px / 2); margin-right: calc(16px / 2); } .framer-ukF83.framer-v-13les4d .framer-4hn12h > :first-child, .framer-ukF83.framer-v-13les4d .framer-sqtetk > :first-child, .framer-ukF83.framer-v-13les4d .framer-14bk1zl > :first-child, .framer-ukF83.framer-v-13les4d .framer-1fc1b7r > :first-child, .framer-ukF83.framer-v-13les4d .framer-7ctwu9 > :first-child, .framer-ukF83.framer-v-13les4d .framer-59alh > :first-child, .framer-ukF83.framer-v-13les4d .framer-1mc6ifp > :first-child { margin-left: 0px; } .framer-ukF83.framer-v-13les4d .framer-4hn12h > :last-child, .framer-ukF83.framer-v-13les4d .framer-sqtetk > :last-child, .framer-ukF83.framer-v-13les4d .framer-14bk1zl > :last-child, .framer-ukF83.framer-v-13les4d .framer-1fc1b7r > :last-child, .framer-ukF83.framer-v-13les4d .framer-7ctwu9 > :last-child, .framer-ukF83.framer-v-13les4d .framer-59alh > :last-child, .framer-ukF83.framer-v-13les4d .framer-1mc6ifp > :last-child { margin-right: 0px; } }",
	...css,
];
var FramersATi3SnVj = withCSS(Component, css2, "framer-ukF83");
var stdin_default = FramersATi3SnVj;
FramersATi3SnVj.displayName = "Services";
FramersATi3SnVj.defaultProps = {
	height: 776,
	width: 1040,
};
addPropertyControls(FramersATi3SnVj, {
	variant: {
		options: [
			"Z3xXhgUUc",
			"MUCjkXBNK",
			"XARj6KQm_",
			"ONBpqfV0W",
			"FikcgJh5c",
			"rq_7lOxBM",
			"T0FL1U0qV",
			"j2MqAs_Oi",
			"ENqozI4SF",
			"h2GSKcPC8",
		],
		optionTitles: [
			"Default",
			"Service 1",
			"Service 2",
			"Service 3",
			"Service 4",
			"Service 5",
			"Service 6",
			"Service 7",
			"Service 8",
			"Mobile",
		],
		title: "Variant",
		type: ControlType.Enum,
	},
	cwup7DuIy: {
		defaultValue: "Service_01",
		description: "",
		displayTextArea: false,
		title: "Service 1",
		type: ControlType.String,
	},
	KliwFVhHo: {
		description: "",
		title: "Service 1",
		type: ControlType.ResponsiveImage,
	},
	shcoV5hhw: {
		defaultValue: "Service_02",
		displayTextArea: false,
		placeholder: "",
		title: "Service 2",
		type: ControlType.String,
	},
	zWAknQVxL: {
		title: "Service 2",
		type: ControlType.ResponsiveImage,
	},
	mVaqMa1We: {
		defaultValue: "Service_03",
		displayTextArea: false,
		title: "Service 3",
		type: ControlType.String,
	},
	uEJS2il6J: {
		title: "Service 3",
		type: ControlType.ResponsiveImage,
	},
	cIOsuIEkl: {
		defaultValue: "Service_04",
		displayTextArea: false,
		title: "Service 4",
		type: ControlType.String,
	},
	Xbv4bIwCr: {
		title: "Service 4",
		type: ControlType.ResponsiveImage,
	},
	jIeFGDszv: {
		defaultValue: "Service_05",
		displayTextArea: false,
		title: "Service 5",
		type: ControlType.String,
	},
	Ar6FZbMbq: {
		title: "Service 5",
		type: ControlType.ResponsiveImage,
	},
	glL7dPde1: {
		defaultValue: "Service_06",
		displayTextArea: false,
		title: "Service 6",
		type: ControlType.String,
	},
	UAL4miu_h: {
		title: "Service 6",
		type: ControlType.ResponsiveImage,
	},
	mwSFKIAbz: {
		defaultValue: "Service_07",
		displayTextArea: false,
		title: "Service 7",
		type: ControlType.String,
	},
	vGI0mfGZO: {
		title: "Service 7",
		type: ControlType.ResponsiveImage,
	},
	VHrllqyHR: {
		defaultValue: "Service_08",
		displayTextArea: false,
		title: "Service 8",
		type: ControlType.String,
	},
	JB6Gdzh2Y: {
		title: "Service 8",
		type: ControlType.ResponsiveImage,
	},
});
addFonts(
	FramersATi3SnVj,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:services
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "h2GSKcPC8",
	xl: "Z3xXhgUUc",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"b917fc1195920e6c8a50255315bde13451700c9dc2ee3323349c54f78331e19f"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ServicesFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"b917fc1195920e6c8a50255315bde13451700c9dc2ee3323349c54f78331e19f"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var services_default = ComponentWithRoot;
export { services_default as default };
