// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project b917fc1195920e6c "Portfolio", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Responsive' // Variant
 * image?: {src: string, srcSet?: string, alt?: string} // Image
 * cursor?: undefined // Cursor
 * title?: string // Title
 * link?: string // Link
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-FPFTPTOS.js";
import { routes } from "./chunks/chunk-MBSQQC4T.js";

// virtual:work
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/lc1jQyaW3lPRrdopXpAU/BNjzl8qeh0KLHA12o1Fm/iP4LR9lMK.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	Link,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var enabledGestures = {
	tVH7Kxs6t: {
		hover: true,
	},
};
var cycleOrder = ["tVH7Kxs6t", "k4uwilHR_"];
var serializationHash = "framer-iF7NM";
var variantClassNames = {
	k4uwilHR_: "framer-v-1uh2wnx",
	tVH7Kxs6t: "framer-v-1olz8xy",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transition1 = {
	delay: 0,
	duration: 0.6,
	ease: [0.49, 0.23, 0.06, 1],
	type: "tween",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	Desktop: "tVH7Kxs6t",
	Responsive: "k4uwilHR_",
};
var getProps = ({
	cursor,
	height,
	id,
	image,
	link,
	title,
	width,
	...props
}) => {
	var _ref, _humanReadableVariantMap_props_variant, _ref1;
	return {
		...props,
		D4xYztBkK: link !== null && link !== void 0 ? link : props.D4xYztBkK,
		DtqlHicpn: image !== null && image !== void 0 ? image : props.DtqlHicpn,
		gIWIBveKF:
			(_ref = title !== null && title !== void 0 ? title : props.gIWIBveKF) !==
				null && _ref !== void 0
				? _ref
				: " Nike Air Force",
		Rkcs44E2g: cursor !== null && cursor !== void 0 ? cursor : props.Rkcs44E2g,
		variant:
			(_ref1 =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref1 !== void 0
				? _ref1
				: "tVH7Kxs6t",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Variants = motion.create(React.Fragment);
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		DtqlHicpn,
		Rkcs44E2g,
		gIWIBveKF,
		D4xYztBkK,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "tVH7Kxs6t",
		enabledGestures,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<Link href={D4xYztBkK} nodeId={"tVH7Kxs6t"}>
						<Image
							{...restProps}
							{...gestureHandlers}
							as={"a"}
							background={{
								alt: "",
								fit: "fill",
							}}
							className={`${cx(scopingClassNames, "framer-1olz8xy", className2, classNames)} framer-19bc7sl`}
							data-framer-cursor={Rkcs44E2g}
							data-framer-name={"Desktop"}
							layoutDependency={layoutDependency}
							layoutId={"tVH7Kxs6t"}
							ref={ref !== null && ref !== void 0 ? ref : ref1}
							style={{
								...style,
							}}
							{...addPropertyOverrides(
								{
									"tVH7Kxs6t-hover": {
										"data-framer-name": void 0,
									},
									k4uwilHR_: {
										"data-framer-name": "Responsive",
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<motion.div
								className={"framer-107nacr"}
								data-framer-name={"Title"}
								layoutDependency={layoutDependency}
								layoutId={"nMJuOYeBa"}
								style={{
									opacity: 0,
								}}
								variants={{
									"tVH7Kxs6t-hover": {
										opacity: 1,
									},
									k4uwilHR_: {
										opacity: 1,
									},
								}}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1yzc4qc"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"ohhiThhq4"}
									style={{
										"--extracted-1eung3n":
											"var(--token-c21010f9-5cb6-4d3d-85fc-4227a6481949, rgb(255, 255, 255))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={gIWIBveKF}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.h4
											className={"framer-styles-preset-v5rub6"}
											data-styles-preset={"CDJ_2sb5e"}
											style={{
												"--framer-text-color":
													"var(--extracted-1eung3n, var(--token-c21010f9-5cb6-4d3d-85fc-4227a6481949, rgb(255, 255, 255)))",
											}}
										>
											{" Nike Air Force"}
										</motion.h4>
									</React.Fragment>
								</RichText>
							</motion.div>
							<motion.div
								className={"framer-1n3chbh"}
								layoutDependency={layoutDependency}
								layoutId={"tdXajsUUb"}
								style={{
									background:
										"linear-gradient(180deg, rgba(0, 0, 0, 0) 0%, rgba(0, 0, 0, 0.4) 100%)",
									opacity: 0,
								}}
								variants={{
									"tVH7Kxs6t-hover": {
										background:
											"linear-gradient(180deg, rgba(0, 0, 0, 0) 0%, rgba(0, 0, 0, 0.5) 100%)",
										opacity: 1,
									},
									k4uwilHR_: {
										opacity: 1,
									},
								}}
							/>
							<Image
								background={{
									alt: "",
									fit: "fill",
									loading: getLoadingLazyAtYPosition(
										((componentViewport === null || componentViewport === void 0
											? void 0
											: componentViewport.y) || 0) +
											(((componentViewport === null ||
											componentViewport === void 0
												? void 0
												: componentViewport.height) || 505) *
												0.49900990099009923 -
												(((componentViewport === null ||
												componentViewport === void 0
													? void 0
													: componentViewport.height) || 505) *
													1) /
													2),
									),
									pixelHeight: 627,
									pixelWidth: 630,
									sizes:
										(componentViewport === null || componentViewport === void 0
											? void 0
											: componentViewport.width) || "100vw",
									...toResponsiveImage(DtqlHicpn),
								}}
								className={"framer-1os7h0b"}
								data-framer-name={"image"}
								layoutDependency={layoutDependency}
								layoutId={"I6jWnE_sd"}
								{...addPropertyOverrides(
									{
										"tVH7Kxs6t-hover": {
											background: {
												alt: "",
												fit: "fill",
												loading: getLoadingLazyAtYPosition(
													((componentViewport === null ||
													componentViewport === void 0
														? void 0
														: componentViewport.y) || 0) +
														(((componentViewport === null ||
														componentViewport === void 0
															? void 0
															: componentViewport.height) || 505) *
															0.49900990099009923 -
															(((componentViewport === null ||
															componentViewport === void 0
																? void 0
																: componentViewport.height) || 505) *
																1.1) /
																2),
												),
												pixelHeight: 627,
												pixelWidth: 630,
												sizes: `calc(${(componentViewport === null || componentViewport === void 0 ? void 0 : componentViewport.width) || "100vw"} * 1.1)`,
												...toResponsiveImage(DtqlHicpn),
											},
										},
									},
									baseVariant,
									gestureVariant,
								)}
							/>
						</Image>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-iF7NM.framer-19bc7sl, .framer-iF7NM .framer-19bc7sl { display: block; }",
	".framer-iF7NM.framer-1olz8xy { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: 505px; justify-content: flex-end; overflow: hidden; padding: 50px; position: relative; text-decoration: none; width: 505px; }",
	".framer-iF7NM .framer-107nacr { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 100%; z-index: 2; }",
	".framer-iF7NM .framer-1yzc4qc { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-iF7NM .framer-1n3chbh { bottom: 0px; flex: none; height: 505px; left: 0px; overflow: hidden; position: absolute; right: 0px; z-index: 1; }",
	".framer-iF7NM .framer-1os7h0b { flex: none; height: 100%; left: calc(49.900990099009924% - 100% / 2); overflow: hidden; position: absolute; top: calc(49.900990099009924% - 100% / 2); width: 100%; z-index: 0; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-iF7NM.framer-1olz8xy, .framer-iF7NM .framer-107nacr { gap: 0px; } .framer-iF7NM.framer-1olz8xy > * { margin: 0px; margin-bottom: calc(10px / 2); margin-top: calc(10px / 2); } .framer-iF7NM.framer-1olz8xy > :first-child { margin-top: 0px; } .framer-iF7NM.framer-1olz8xy > :last-child { margin-bottom: 0px; } .framer-iF7NM .framer-107nacr > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-iF7NM .framer-107nacr > :first-child { margin-left: 0px; } .framer-iF7NM .framer-107nacr > :last-child { margin-right: 0px; } }",
	".framer-iF7NM.framer-v-1uh2wnx.framer-1olz8xy { aspect-ratio: 1 / 1; cursor: unset; height: var(--framer-aspect-ratio-supported, 505px); padding: 34px; }",
	".framer-iF7NM.framer-v-1olz8xy.hover.framer-1olz8xy { aspect-ratio: 1 / 1; height: var(--framer-aspect-ratio-supported, 505px); }",
	".framer-iF7NM.framer-v-1olz8xy.hover .framer-1os7h0b { height: 110%; left: calc(49.900990099009924% - 110.00000000000001% / 2); top: calc(49.900990099009924% - 110.00000000000001% / 2); width: 110%; }",
	...css,
];
var FrameriP4LR9lMK = withCSS(Component, css2, "framer-iF7NM");
var stdin_default = FrameriP4LR9lMK;
FrameriP4LR9lMK.displayName = "Work";
FrameriP4LR9lMK.defaultProps = {
	height: 505,
	width: 505,
};
addPropertyControls(FrameriP4LR9lMK, {
	variant: {
		options: ["tVH7Kxs6t", "k4uwilHR_"],
		optionTitles: ["Desktop", "Responsive"],
		title: "Variant",
		type: ControlType.Enum,
	},
	DtqlHicpn: {
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
	Rkcs44E2g: {
		title: "Cursor",
		type: ControlType.CustomCursor,
	},
	gIWIBveKF: {
		defaultValue: " Nike Air Force",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	D4xYztBkK: {
		title: "Link",
		type: ControlType.Link,
	},
});
addFonts(
	FrameriP4LR9lMK,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/vQyevYAyHtARFwPqUzQGpnDs.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:work
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "k4uwilHR_",
	xl: "tVH7Kxs6t",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"b917fc1195920e6c8a50255315bde13451700c9dc2ee3323349c54f78331e19f"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders WorkFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"b917fc1195920e6c8a50255315bde13451700c9dc2ee3323349c54f78331e19f"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var work_default = ComponentWithRoot;
export { work_default as default };
